// catalogo-activos.js — catálogo de nombres para el alta de posiciones.
// GENERADO el 23/09/2026 por generar_catalogo.py: no editar a mano, regenerar
// (python generar_catalogo.py; con --refrescar vuelve a bajar las fuentes).
// El generador vive en C:\Users\lauti\AppData\Local\Temp\claude\C--Users-lauti-Downloads-Valtia-Anlaytics-Valtia-Anlaytics\0063cacc-c090-4ad6-947d-9742dfe0c8a8\scratchpad
// Solo símbolo y nombre: nunca precios ni datos de mercado.
//
// Cada entrada: { s: símbolo como lo ve el usuario, n: nombre, t: tipo, m: mercado }
//   t: cedear | accion_ar | accion_us | etf | bono | letra | on | cripto
//   m: byma (cotiza en pesos en BYMA) · ext (NYSE / Nasdaq, en dólares) · cripto
// Un mismo símbolo puede estar en dos mercados (AAPL es CEDEAR en BYMA y acción
// en el exterior): son dos entradas, y buscarCatalogo(simbolo, mercado) elige.
//
// FUENTES (listas públicas de referencia; nombres tal cual los publica cada una)
//   1 CEDEARs: "CEDEARs Negociables en BYMA", nómina oficial del 16/09/2026
//     https://cdn.prod.website-files.com/6697a441a50c6b926e1972e0/6ab2a2889b5ecd166f88f930_2026-09-16-BYMA-CEDEARs.pdf
//   2 Acciones argentinas: Wikipedia "S&P Merval" (tablas panel líder y general)
//     https://es.wikipedia.org/wiki/S%26P_Merval
//     filtradas contra el panel de acciones de BYMA (open data, solo el símbolo)
//     https://open.bymadata.com.ar/vanoms-be-core/rest/api/bymadata/free/general-equity · leading-equity
//     y con los nombres que ya publica el sitio en empresas.js
//   3 Acciones de EE.UU.: Wikipedia "List of S&P 500 companies" y
//     "List of NASDAQ-100 companies"
//     https://en.wikipedia.org/wiki/List_of_S%26P_500_companies
//     https://en.wikipedia.org/wiki/List_of_NASDAQ-100_companies
//   4 ETFs: lista curada de los más operados, con el nombre oficial del emisor
//     (está en ETFS dentro de generar_catalogo.py)
//   5 Renta fija: bonosPanel/latest del sitio (arreglo "todos", secciones y
//     vencimientos). El nombre sale de la familia de la especie (Bonar, Global,
//     Bopreal, Lecap, Lecer, Boncer, dólar linked, cupón PBI, Discount, Par,
//     Cuasipar, Bonte, Córdoba, PBA 2037, CABA); lo que no es inequívoco queda
//     como "Renta fija BYMA · panel de bonos" con su vencimiento.
//   6 Cripto: CoinGecko, 100 de mayor capitalización (symbol + name)
//     https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1
//
// Cantidades:
//     byma   accion_ar     58
//     byma   bono         221
//     byma   cedear       445
//     byma   letra         17
//     cripto cripto        99
//     ext    accion_us    526
//     ext    etf          103
//     total  1469

export const CATALOGO = [
  {s:"AABA",n:"Altaba Inc.",t:"cedear",m:"byma"},
  {s:"AAL",n:"American Airlines Group Inc",t:"cedear",m:"byma"},
  {s:"AAP",n:"Advanced Auto Parts Inc",t:"cedear",m:"byma"},
  {s:"AAPL",n:"Apple Inc.",t:"cedear",m:"byma"},
  {s:"ABBV",n:"AbbVie Inc.",t:"cedear",m:"byma"},
  {s:"ABEV",n:"Ambev S.A.",t:"cedear",m:"byma"},
  {s:"ABEV3",n:"Ambev S.A.",t:"cedear",m:"byma"},
  {s:"ABNB",n:"Airbnb Inc",t:"cedear",m:"byma"},
  {s:"ABT",n:"Abbott Labs",t:"cedear",m:"byma"},
  {s:"ACN",n:"Accenture",t:"cedear",m:"byma"},
  {s:"ACWI",n:"iShares MSCI ACWI ETF",t:"cedear",m:"byma"},
  {s:"ADBE",n:"Adobe Systems Incorporated",t:"cedear",m:"byma"},
  {s:"ADGO",n:"Adecoagro S.A.",t:"cedear",m:"byma"},
  {s:"ADI",n:"Analog Devices",t:"cedear",m:"byma"},
  {s:"ADP",n:"Automatic Data Processing Inc.",t:"cedear",m:"byma"},
  {s:"ADS",n:"Adidas AG",t:"cedear",m:"byma"},
  {s:"AEG",n:"Aegon N.V.",t:"cedear",m:"byma"},
  {s:"AEM",n:"Agnico Eagle Mines Limited",t:"cedear",m:"byma"},
  {s:"AI",n:"C3.AI INC",t:"cedear",m:"byma"},
  {s:"AIG",n:"American International Group (AIG)",t:"cedear",m:"byma"},
  {s:"AKO.B",n:"Embotelladora Andina S.A.",t:"cedear",m:"byma"},
  {s:"ALAB",n:"Astera Labs Inc",t:"cedear",m:"byma"},
  {s:"AMAT",n:"Applied Materials Inc.",t:"cedear",m:"byma"},
  {s:"AMD",n:"Advanced Micro Devices, Inc.",t:"cedear",m:"byma"},
  {s:"AMGN",n:"Amgen Inc.",t:"cedear",m:"byma"},
  {s:"AMX",n:"America Movil",t:"cedear",m:"byma"},
  {s:"AMZN",n:"Amazon.Com, Inc.",t:"cedear",m:"byma"},
  {s:"ANET",n:"Arista Networks Inc.",t:"cedear",m:"byma"},
  {s:"ANF",n:"Abercrombie & Fitch Co",t:"cedear",m:"byma"},
  {s:"AOCA",n:"Aluminum Corp Of China",t:"cedear",m:"byma"},
  {s:"ARCO",n:"Arcos Dorados Holdings Inc.",t:"cedear",m:"byma"},
  {s:"ARKK",n:"ARK INNOVATION",t:"cedear",m:"byma"},
  {s:"ARM",n:"ARM Holdings Plc",t:"cedear",m:"byma"},
  {s:"ASML",n:"ASML HOLDING NV",t:"cedear",m:"byma"},
  {s:"ASR",n:"Grupo Aeroportuario Del Sureste , S.A.B. de C.V.",t:"cedear",m:"byma"},
  {s:"ASTS",n:"AST SpaceMobile Inc",t:"cedear",m:"byma"},
  {s:"ATAD",n:"Pjsc Tatneft",t:"cedear",m:"byma"},
  {s:"AUY",n:"Yamana Gold Inc.",t:"cedear",m:"byma"},
  {s:"AVGO",n:"Broadcom Inc.",t:"cedear",m:"byma"},
  {s:"AVY",n:"Avery Dennison Corp.",t:"cedear",m:"byma"},
  {s:"AXP",n:"American Express Co",t:"cedear",m:"byma"},
  {s:"AZN",n:"Astrazeneca Plc",t:"cedear",m:"byma"},
  {s:"B",n:"Barrick Gold Corp",t:"cedear",m:"byma"},
  {s:"BA",n:"The Boeing Company",t:"cedear",m:"byma"},
  {s:"BA.C",n:"Bank Of America Corporation",t:"cedear",m:"byma"},
  {s:"BABA",n:"Alibaba Group Holding Limited",t:"cedear",m:"byma"},
  {s:"BAK",n:"Braskem SA",t:"cedear",m:"byma"},
  {s:"BAS",n:"Basf SE",t:"cedear",m:"byma"},
  {s:"BAYN",n:"Bayer AG",t:"cedear",m:"byma"},
  {s:"BB",n:"Blackberry Limited",t:"cedear",m:"byma"},
  {s:"BBAS3",n:"Banco do Brasil S.A.",t:"cedear",m:"byma"},
  {s:"BBAX",n:"JPMorgan BetaBuilders Developed Asia Pacific-ex Japan ETF",t:"cedear",m:"byma"},
  {s:"BBCA",n:"JPMorgan BetaBuilders Canada ETF",t:"cedear",m:"byma"},
  {s:"BBD",n:"Banco Bradesco S.A.",t:"cedear",m:"byma"},
  {s:"BBDC3",n:"Banco Bradesco S.A.",t:"cedear",m:"byma"},
  {s:"BBV",n:"Bilbao Vizcaya Argentaria S.A.",t:"cedear",m:"byma"},
  {s:"BCS",n:"Barclays Bank Plc",t:"cedear",m:"byma"},
  {s:"BHP",n:"Bhp Group Ltd",t:"cedear",m:"byma"},
  {s:"BIDU",n:"Baidu, Inc.",t:"cedear",m:"byma"},
  {s:"BIIB",n:"Biogen Inc.",t:"cedear",m:"byma"},
  {s:"BIOX",n:"Bioceres Crop Solutions Corp.",t:"cedear",m:"byma"},
  {s:"BK",n:"The Bank Of New York Mellon Corp.",t:"cedear",m:"byma"},
  {s:"BKNG",n:"Booking",t:"cedear",m:"byma"},
  {s:"BKR",n:"Baker Hughes Co",t:"cedear",m:"byma"},
  {s:"BMNR",n:"Bitmine Inmersion Technologies, Inc.",t:"cedear",m:"byma"},
  {s:"BMY",n:"Bristol-Myers Squibb Company",t:"cedear",m:"byma"},
  {s:"BNG",n:"Bunge Limited",t:"cedear",m:"byma"},
  {s:"BP",n:"BP PCL",t:"cedear",m:"byma"},
  {s:"BPA11",n:"Banco BTG Pactual S.A.",t:"cedear",m:"byma"},
  {s:"BRFS",n:"BRF S.A.",t:"cedear",m:"byma"},
  {s:"BRKB",n:"Berkshire Hathaway Inc.",t:"cedear",m:"byma"},
  {s:"BSBR",n:"Banco Santander (Brasil) S.A.",t:"cedear",m:"byma"},
  {s:"BSN",n:"Danone",t:"cedear",m:"byma"},
  {s:"BX",n:"Blackstone Inc.",t:"cedear",m:"byma"},
  {s:"C",n:"Citigroup Inc",t:"cedear",m:"byma"},
  {s:"CAAP",n:"Corporación America Airports S.A.",t:"cedear",m:"byma"},
  {s:"CAH",n:"Cardinal Health Inc",t:"cedear",m:"byma"},
  {s:"CAJ",n:"Canon Inc",t:"cedear",m:"byma"},
  {s:"CAR",n:"Avis Budget Group Inc.",t:"cedear",m:"byma"},
  {s:"CAT",n:"Caterpillar Inc",t:"cedear",m:"byma"},
  {s:"CBRD",n:"Companhia Brasileira De Dis NPV ADR",t:"cedear",m:"byma"},
  {s:"CCJ",n:"Cameco Corporation",t:"cedear",m:"byma"},
  {s:"CCL",n:"Carnival",t:"cedear",m:"byma"},
  {s:"CDE",n:"Coeur Mining Inc.",t:"cedear",m:"byma"},
  {s:"CEG",n:"CONSTELLATION ENERGY CORPORATION",t:"cedear",m:"byma"},
  {s:"CIBR",n:"First Trust NASDAQ Cybersecurity",t:"cedear",m:"byma"},
  {s:"CL",n:"Colgate Palmolive Co",t:"cedear",m:"byma"},
  {s:"CLS",n:"CELESTICA INC",t:"cedear",m:"byma"},
  {s:"COIN",n:"Coinbase Global Inc",t:"cedear",m:"byma"},
  {s:"COP",n:"ConocoPhillips",t:"cedear",m:"byma"},
  {s:"COPX",n:"Global X Copper Miners ETF",t:"cedear",m:"byma"},
  {s:"CORN",n:"Teucrium Corn Fund",t:"cedear",m:"byma"},
  {s:"COST",n:"Costco Wholesale Corp",t:"cedear",m:"byma"},
  {s:"CRM",n:"Salesforce Inc.",t:"cedear",m:"byma"},
  {s:"CRWD",n:"CrowdStrike Holdings, Inc.",t:"cedear",m:"byma"},
  {s:"CRWV",n:"CoreWeave Inc",t:"cedear",m:"byma"},
  {s:"CS",n:"Credit Suisse Group",t:"cedear",m:"byma"},
  {s:"CSCO",n:"Cisco Systems Inc",t:"cedear",m:"byma"},
  {s:"CSNA3",n:"Companhia Siderúrgica Nacional S.A.",t:"cedear",m:"byma"},
  {s:"CVS",n:"CVS Health",t:"cedear",m:"byma"},
  {s:"CVX",n:"Chevron Corp.",t:"cedear",m:"byma"},
  {s:"CX",n:"Cemex S.A.B. de CV",t:"cedear",m:"byma"},
  {s:"DAL",n:"Delta Air Lines",t:"cedear",m:"byma"},
  {s:"DD",n:"Dupont de Nemours Inc.",t:"cedear",m:"byma"},
  {s:"DE",n:"Deere & Co.",t:"cedear",m:"byma"},
  {s:"DECK",n:"DECKERS OUTDOOR CORPORATION",t:"cedear",m:"byma"},
  {s:"DELL",n:"DELL TECHNOLOGIES INC",t:"cedear",m:"byma"},
  {s:"DEO",n:"Diageo PLC",t:"cedear",m:"byma"},
  {s:"DHR",n:"Danaher Corp",t:"cedear",m:"byma"},
  {s:"DIA",n:"SPDR DOW JONES INDUSTRIAL",t:"cedear",m:"byma"},
  {s:"DISN",n:"The Walt Disney Co.",t:"cedear",m:"byma"},
  {s:"DOCU",n:"DocuSign Inc.",t:"cedear",m:"byma"},
  {s:"DOW",n:"DOW Inc",t:"cedear",m:"byma"},
  {s:"DTEA",n:"Deutsche Telekom Ag",t:"cedear",m:"byma"},
  {s:"E",n:"Eni Spa",t:"cedear",m:"byma"},
  {s:"EA",n:"Electronic Arts Inc",t:"cedear",m:"byma"},
  {s:"EBAY",n:"Ebay Inc.",t:"cedear",m:"byma"},
  {s:"EBR",n:"Centrais Eléctricas Brasileiras S.A. - Eletrobras",t:"cedear",m:"byma"},
  {s:"ECL",n:"Ecolab Inc",t:"cedear",m:"byma"},
  {s:"EEM",n:"ISHARES MSCI EMERGING MARKET",t:"cedear",m:"byma"},
  {s:"EFA",n:"iShares MSCI EAFE ETF",t:"cedear",m:"byma"},
  {s:"EFX",n:"Equifax Inc.",t:"cedear",m:"byma"},
  {s:"ELP",n:"Companhia Paranaense de Energía - COPEL",t:"cedear",m:"byma"},
  {s:"EOAN",n:"E.On Se",t:"cedear",m:"byma"},
  {s:"EQNR",n:"Equinor Asa",t:"cedear",m:"byma"},
  {s:"ERIC",n:"Lm Ericsson Telephone Co.",t:"cedear",m:"byma"},
  {s:"ERJ",n:"Embraer-Empresa Brasileira de Aeronáutica S.A.",t:"cedear",m:"byma"},
  {s:"ESGU",n:"IShares ESG Aware MSCI USA ETF",t:"cedear",m:"byma"},
  {s:"ETHA",n:"ISHARES ETHEREUM TR ETF",t:"cedear",m:"byma"},
  {s:"ETSY",n:"Etsy Inc.",t:"cedear",m:"byma"},
  {s:"EWJ",n:"iShares MSCI JAPAN ETF",t:"cedear",m:"byma"},
  {s:"EWY",n:"iShares MSCI South Korea ETF",t:"cedear",m:"byma"},
  {s:"EWZ",n:"ISHARES MSCI BRAZIL CAP",t:"cedear",m:"byma"},
  {s:"F",n:"Ford Motor Company",t:"cedear",m:"byma"},
  {s:"FCX",n:"Freeport Mcmoran Copper & Gold Inc.",t:"cedear",m:"byma"},
  {s:"FDX",n:"Fedex Corp",t:"cedear",m:"byma"},
  {s:"FISV",n:"Fiserv, Inc.",t:"cedear",m:"byma"},
  {s:"FMCC",n:"Freddie Mac (Federal Home Loan)",t:"cedear",m:"byma"},
  {s:"FMX",n:"Fomento Economico Mexicano - Femsa",t:"cedear",m:"byma"},
  {s:"FNMA",n:"Fed. Natl, Mortgage - Fannie Mae",t:"cedear",m:"byma"},
  {s:"FSLR",n:"First Solar Inc.",t:"cedear",m:"byma"},
  {s:"FXI",n:"ISHARES CHINA LARGE-CAP ETF",t:"cedear",m:"byma"},
  {s:"GDX",n:"Van Eck Gold Miners ETF/USA",t:"cedear",m:"byma"},
  {s:"GE",n:"General Electric Co.",t:"cedear",m:"byma"},
  {s:"GEV",n:"GE VERNOVA INC",t:"cedear",m:"byma"},
  {s:"GFI",n:"Gold Fields Ltd.",t:"cedear",m:"byma"},
  {s:"GGB",n:"Gerdau S.A.",t:"cedear",m:"byma"},
  {s:"GILD",n:"Gilead Sciences, Inc.",t:"cedear",m:"byma"},
  {s:"GLD",n:"ETF SPDR GOLD TRUST",t:"cedear",m:"byma"},
  {s:"GLNG",n:"Golar LNG Ltd.",t:"cedear",m:"byma"},
  {s:"GLOB",n:"Globant S.A.",t:"cedear",m:"byma"},
  {s:"GLW",n:"Corning Inc.",t:"cedear",m:"byma"},
  {s:"GM",n:"General Motors Co",t:"cedear",m:"byma"},
  {s:"GOOGL",n:"Alphabet Inc.",t:"cedear",m:"byma"},
  {s:"GPRK",n:"Geopark Ltd.",t:"cedear",m:"byma"},
  {s:"GRMN",n:"Garmin Ltd.",t:"cedear",m:"byma"},
  {s:"GS",n:"The Goldman Sachs Group, Inc",t:"cedear",m:"byma"},
  {s:"GSG",n:"iShares S&P GSCI Commodity-Indexed Trust",t:"cedear",m:"byma"},
  {s:"GSK",n:"GSK Plc.",t:"cedear",m:"byma"},
  {s:"GT",n:"Goodyear Tire & Rubber co./the",t:"cedear",m:"byma"},
  {s:"HAL",n:"Halliburton Co.",t:"cedear",m:"byma"},
  {s:"HAPV3",n:"Hapvida Participacoes E Investimentos S.A.",t:"cedear",m:"byma"},
  {s:"HD",n:"The Home Depot Inc.",t:"cedear",m:"byma"},
  {s:"HDB",n:"Hdfc Bank Limited.",t:"cedear",m:"byma"},
  {s:"HHPD",n:"Hon Hai Precision Industry Co. Ltd.",t:"cedear",m:"byma"},
  {s:"HIMS",n:"Hims & Hers Health, Inc.",t:"cedear",m:"byma"},
  {s:"HL",n:"Hecla Mining Co .",t:"cedear",m:"byma"},
  {s:"HMC",n:"Honda Motor Co. Ltd",t:"cedear",m:"byma"},
  {s:"HMY",n:"Harmony Gold Mining Company Ltd.",t:"cedear",m:"byma"},
  {s:"HNPIY",n:"Huaneng Power Intl",t:"cedear",m:"byma"},
  {s:"HOG",n:"Harley-Davidson Inc.",t:"cedear",m:"byma"},
  {s:"HON",n:"Honeywell International Inc.",t:"cedear",m:"byma"},
  {s:"HOOD",n:"Robinhood Markets Inc",t:"cedear",m:"byma"},
  {s:"HPQ",n:"Hp Inc",t:"cedear",m:"byma"},
  {s:"HSBC",n:"Hsbc Holdings Plc",t:"cedear",m:"byma"},
  {s:"HSY",n:"The Hershey Company",t:"cedear",m:"byma"},
  {s:"HUT",n:"Hut 8 Mining Corp.",t:"cedear",m:"byma"},
  {s:"HWM",n:"Howmet Aerospace Inc.",t:"cedear",m:"byma"},
  {s:"IBB",n:"iShares Nasdaq Biotechnology ETF",t:"cedear",m:"byma"},
  {s:"IBIT",n:"ISHARES BITCOIN TRUST",t:"cedear",m:"byma"},
  {s:"IBKR",n:"INTERACTIVE BROKERS GROUP INC",t:"cedear",m:"byma"},
  {s:"IBM",n:"International Business Machines",t:"cedear",m:"byma"},
  {s:"IBN",n:"Icici Bank Ltd.",t:"cedear",m:"byma"},
  {s:"ICLN",n:"iShares Global Clean Energy ETF",t:"cedear",m:"byma"},
  {s:"IEMG",n:"iShares Core MSCI Emerging Markets ETF",t:"cedear",m:"byma"},
  {s:"IEUR",n:"iShares Core MSCI Europe ETF",t:"cedear",m:"byma"},
  {s:"IFF",n:"International Flavors & Fragrances Inc.",t:"cedear",m:"byma"},
  {s:"IJH",n:"iShares CORE S&P MID-CAP ETF",t:"cedear",m:"byma"},
  {s:"ILF",n:"IShares Latin America 40 ETF",t:"cedear",m:"byma"},
  {s:"INFY",n:"Infosys Limited",t:"cedear",m:"byma"},
  {s:"ING",n:"Ing Groep Nv",t:"cedear",m:"byma"},
  {s:"INTC",n:"Intel Corporation",t:"cedear",m:"byma"},
  {s:"IP",n:"International Paper Co.",t:"cedear",m:"byma"},
  {s:"IREN",n:"Iren Ltd",t:"cedear",m:"byma"},
  {s:"ISRG",n:"Intuitive Surgical inc",t:"cedear",m:"byma"},
  {s:"ITA",n:"iShares U.S. Aerospace & Defense",t:"cedear",m:"byma"},
  {s:"ITUB",n:"Itaú Unibanco Holding S.A.",t:"cedear",m:"byma"},
  {s:"ITUB3",n:"Banco Itaú Unibanco S.A",t:"cedear",m:"byma"},
  {s:"IVE",n:"iShares S&P 500 Value ETF",t:"cedear",m:"byma"},
  {s:"IVV",n:"IShares Core S&P 500 ETF",t:"cedear",m:"byma"},
  {s:"IVW",n:"iShares S&P 500 Growth ETF",t:"cedear",m:"byma"},
  {s:"IWM",n:"ISHARES TRUST RUSSELL 2000",t:"cedear",m:"byma"},
  {s:"JCI",n:"Johnson Controls International",t:"cedear",m:"byma"},
  {s:"JD",n:"Jd.Com, Inc.",t:"cedear",m:"byma"},
  {s:"JMIA",n:"Adr Jumia Technologies Ag",t:"cedear",m:"byma"},
  {s:"JNJ",n:"Johnson & Johnson",t:"cedear",m:"byma"},
  {s:"JOYY",n:"JOYY Inc.",t:"cedear",m:"byma"},
  {s:"JPM",n:"J.P. Morgan & Chase Co.",t:"cedear",m:"byma"},
  {s:"KB",n:"Kb Financial Group Inc.",t:"cedear",m:"byma"},
  {s:"KEEL",n:"Bitfarms Ltd.",t:"cedear",m:"byma"},
  {s:"KEP",n:"Korea Electric Power Corp.",t:"cedear",m:"byma"},
  {s:"KGC",n:"Kinross Gold Corp",t:"cedear",m:"byma"},
  {s:"KLAC",n:"KLA CORP",t:"cedear",m:"byma"},
  {s:"KMB",n:"Kimberly-Clark Corp.",t:"cedear",m:"byma"},
  {s:"KO",n:"The Coca Cola Company",t:"cedear",m:"byma"},
  {s:"KOFM",n:"Coca-Cola Femsa, S.A.B. De C.V.",t:"cedear",m:"byma"},
  {s:"LAC",n:"Lithium Americas Corp",t:"cedear",m:"byma"},
  {s:"LAR",n:"Lithium Americas (Argentina) Corp",t:"cedear",m:"byma"},
  {s:"LFC",n:"China Life Insurance",t:"cedear",m:"byma"},
  {s:"LIN",n:"LINDE PLC",t:"cedear",m:"byma"},
  {s:"LKOD",n:"Pjsc Lukoil",t:"cedear",m:"byma"},
  {s:"LLY",n:"Eli Lilly and Company",t:"cedear",m:"byma"},
  {s:"LMT",n:"Lockheed Martin Corporation",t:"cedear",m:"byma"},
  {s:"LND",n:"Brasilagro - Co Brasileira de Propriedades Agrícolas",t:"cedear",m:"byma"},
  {s:"LRCX",n:"Lam Research Corp",t:"cedear",m:"byma"},
  {s:"LREN3",n:"Lojas Renner S.A.",t:"cedear",m:"byma"},
  {s:"LVS",n:"Las Vegas Sands Corp",t:"cedear",m:"byma"},
  {s:"LYG",n:"Lloyds Banking Group Plc",t:"cedear",m:"byma"},
  {s:"MA",n:"Mastercard Inc.",t:"cedear",m:"byma"},
  {s:"MBG",n:"Mercedes-Benz Group AG",t:"cedear",m:"byma"},
  {s:"MBT",n:"Mobile Telesystems",t:"cedear",m:"byma"},
  {s:"MCD",n:"Mcdonald'S Corp.",t:"cedear",m:"byma"},
  {s:"MDLZ",n:"Mondelez",t:"cedear",m:"byma"},
  {s:"MDT",n:"Medtronic Public Limited Company",t:"cedear",m:"byma"},
  {s:"MELI",n:"Mercadolibre Inc.",t:"cedear",m:"byma"},
  {s:"META",n:"Meta Platforms Inc",t:"cedear",m:"byma"},
  {s:"MFG",n:"Mizuho Financial Group",t:"cedear",m:"byma"},
  {s:"MGLU3",n:"Magazine Luiza S.A.",t:"cedear",m:"byma"},
  {s:"MMC",n:"Marsh & Mclennan Companies Inc.",t:"cedear",m:"byma"},
  {s:"MMM",n:"3M Company",t:"cedear",m:"byma"},
  {s:"MO",n:"Altria Group Inc.",t:"cedear",m:"byma"},
  {s:"MOS",n:"The Mosaic Co",t:"cedear",m:"byma"},
  {s:"MP",n:"MP Materials Corp.",t:"cedear",m:"byma"},
  {s:"MRK",n:"Merck & Co. Inc.",t:"cedear",m:"byma"},
  {s:"MRNA",n:"Moderna Inc",t:"cedear",m:"byma"},
  {s:"MRVL",n:"Marvell Technology Inc",t:"cedear",m:"byma"},
  {s:"MS",n:"MORGAN STANLEY",t:"cedear",m:"byma"},
  {s:"MSFT",n:"Microsoft Corp.",t:"cedear",m:"byma"},
  {s:"MSI",n:"Motorola Solutions, Inc.",t:"cedear",m:"byma"},
  {s:"MSTR",n:"Microstrategy Inc Cl A New",t:"cedear",m:"byma"},
  {s:"MU",n:"Micron Technology Inc",t:"cedear",m:"byma"},
  {s:"MUFG",n:"Mitsubishi Ufj Financial Group",t:"cedear",m:"byma"},
  {s:"MUX",n:"McEwen Mining Inc",t:"cedear",m:"byma"},
  {s:"NATU3",n:"NATURA COSMETICOS SA",t:"cedear",m:"byma"},
  {s:"NBIS",n:"Nebius Group N.V.",t:"cedear",m:"byma"},
  {s:"NEC1",n:"Nec Corporation",t:"cedear",m:"byma"},
  {s:"NEE",n:"NextEra Energy, Inc.",t:"cedear",m:"byma"},
  {s:"NEM",n:"Newmont Corporation",t:"cedear",m:"byma"},
  {s:"NFLX",n:"Netflix, Inc.",t:"cedear",m:"byma"},
  {s:"NG",n:"Novagold Resources INC.",t:"cedear",m:"byma"},
  {s:"NGG",n:"National Grid Plc",t:"cedear",m:"byma"},
  {s:"NIO",n:"NIO Inc.",t:"cedear",m:"byma"},
  {s:"NKE",n:"Nike Inc.",t:"cedear",m:"byma"},
  {s:"NLM",n:"Novolipetsk Steel PJSC",t:"cedear",m:"byma"},
  {s:"NMR",n:"Nomura Holdings, Inc",t:"cedear",m:"byma"},
  {s:"NOKA",n:"Nokia Corporation",t:"cedear",m:"byma"},
  {s:"NOW",n:"SERVICENOW INC",t:"cedear",m:"byma"},
  {s:"NSAN",n:"Nissan Motor Co., Ltd",t:"cedear",m:"byma"},
  {s:"NTES",n:"Netease, Inc",t:"cedear",m:"byma"},
  {s:"NTRA",n:"NATERA INC",t:"cedear",m:"byma"},
  {s:"NUE",n:"Nucor Corp",t:"cedear",m:"byma"},
  {s:"NVDA",n:"Nvidia Corporation",t:"cedear",m:"byma"},
  {s:"NVO",n:"NOVO NORDISK A/S",t:"cedear",m:"byma"},
  {s:"NVS",n:"Novartis Ag",t:"cedear",m:"byma"},
  {s:"NXE",n:"Nexgen Energy LTD",t:"cedear",m:"byma"},
  {s:"O",n:"Realty Income Corp.",t:"cedear",m:"byma"},
  {s:"OGZD",n:"Pjsc Gazprom",t:"cedear",m:"byma"},
  {s:"OKLO",n:"Oklo Inc",t:"cedear",m:"byma"},
  {s:"ONDS",n:"Ondas Holdings Inc.",t:"cedear",m:"byma"},
  {s:"ORAN",n:"Orange S.A.",t:"cedear",m:"byma"},
  {s:"ORCL",n:"Oracle Corporation",t:"cedear",m:"byma"},
  {s:"ORLY",n:"O'reilly Automotive Inc",t:"cedear",m:"byma"},
  {s:"OXY",n:"Occidental Petroleum Corp.",t:"cedear",m:"byma"},
  {s:"PAAS",n:"Pan American Silver Corp.",t:"cedear",m:"byma"},
  {s:"PAC",n:"Grupo Aeroportuario del Pacifico, S.A.B. de C.V.",t:"cedear",m:"byma"},
  {s:"PAGS",n:"Pagseguro Digital Ltd",t:"cedear",m:"byma"},
  {s:"PANW",n:"Palo Alto Networks Inc",t:"cedear",m:"byma"},
  {s:"PATH",n:"UIPATH INC",t:"cedear",m:"byma"},
  {s:"PBI",n:"Pitney Bowes Inc",t:"cedear",m:"byma"},
  {s:"PBR",n:"Petrobras (ADR)",t:"cedear",m:"byma"},
  {s:"PCAR",n:"Paccar Inc.",t:"cedear",m:"byma"},
  {s:"PCRF",n:"Panasonic Corporation",t:"cedear",m:"byma"},
  {s:"PDD",n:"PDD HOLDINGS INC",t:"cedear",m:"byma"},
  {s:"PEP",n:"Pepsico Inc",t:"cedear",m:"byma"},
  {s:"PETR3",n:"Petrobras - Petróleo Brasileiro S.A.",t:"cedear",m:"byma"},
  {s:"PFE",n:"Pfizer Inc.",t:"cedear",m:"byma"},
  {s:"PG",n:"Procter & Gamble",t:"cedear",m:"byma"},
  {s:"PHG",n:"Koninklijke Philips N.V.",t:"cedear",m:"byma"},
  {s:"PINS",n:"Pinterest",t:"cedear",m:"byma"},
  {s:"PKS",n:"Posco Holdings Inc.",t:"cedear",m:"byma"},
  {s:"PLD",n:"PROLOGIS INC",t:"cedear",m:"byma"},
  {s:"PLTR",n:"Palantir Technologies Inc",t:"cedear",m:"byma"},
  {s:"PM",n:"Philip Morris International",t:"cedear",m:"byma"},
  {s:"PRIO3",n:"Petro Rio S.A.",t:"cedear",m:"byma"},
  {s:"PSO",n:"Pearson Plc",t:"cedear",m:"byma"},
  {s:"PSQ",n:"PROSHARES SHORT QQQ",t:"cedear",m:"byma"},
  {s:"PSX",n:"Phillips 66",t:"cedear",m:"byma"},
  {s:"PTR",n:"Petrochina Co Ltd",t:"cedear",m:"byma"},
  {s:"PYPL",n:"Paypal Holdings, Inc.",t:"cedear",m:"byma"},
  {s:"QCOM",n:"Qualcomm Inc.",t:"cedear",m:"byma"},
  {s:"QQQ",n:"INVESCO QQQ TRUST",t:"cedear",m:"byma"},
  {s:"RACE",n:"Ferrari",t:"cedear",m:"byma"},
  {s:"RBLX",n:"Roblox Corp.",t:"cedear",m:"byma"},
  {s:"RCTB4",n:"Telebras PN",t:"cedear",m:"byma"},
  {s:"RENT3",n:"Localiza Rent A Car S.A.",t:"cedear",m:"byma"},
  {s:"RGTI",n:"RIGETTI COMPUTING INC",t:"cedear",m:"byma"},
  {s:"RIO",n:"Rio Tinto Plc",t:"cedear",m:"byma"},
  {s:"RIOT",n:"Riot Platforms",t:"cedear",m:"byma"},
  {s:"RKLB",n:"Rocket Lab Corp",t:"cedear",m:"byma"},
  {s:"ROKU",n:"Roku",t:"cedear",m:"byma"},
  {s:"ROST",n:"Ross Stores, Inc.",t:"cedear",m:"byma"},
  {s:"RSP",n:"Invesco S&P 500 eql wght ETF",t:"cedear",m:"byma"},
  {s:"RTX",n:"Raytheon Technologies Corp",t:"cedear",m:"byma"},
  {s:"SAN",n:"Banco Santander S.A",t:"cedear",m:"byma"},
  {s:"SAP",n:"Sap Se",t:"cedear",m:"byma"},
  {s:"SATL",n:"Satellogic Inc.",t:"cedear",m:"byma"},
  {s:"SBS",n:"Companhia de Saneamento Básico do Estado de São Paulo Sabesp",t:"cedear",m:"byma"},
  {s:"SBSP3",n:"Cia Saneamento Básico de SP",t:"cedear",m:"byma"},
  {s:"SBUX",n:"Starbucks Corporation",t:"cedear",m:"byma"},
  {s:"SCCO",n:"Southern Copper Corp",t:"cedear",m:"byma"},
  {s:"SCHW",n:"Charles Schwab",t:"cedear",m:"byma"},
  {s:"SDA",n:"SunCar Technology Group Inc",t:"cedear",m:"byma"},
  {s:"SE",n:"Sea Ltd.",t:"cedear",m:"byma"},
  {s:"SH",n:"PROSHARES SHORT S&P500",t:"cedear",m:"byma"},
  {s:"SHEL",n:"Royal Dutch Shell Plc",t:"cedear",m:"byma"},
  {s:"SHOP",n:"Shopify Inc.",t:"cedear",m:"byma"},
  {s:"SHPW",n:"Shapeways Holdings Inc",t:"cedear",m:"byma"},
  {s:"SHW",n:"SHERWIN-WILLIAMS CO/THE",t:"cedear",m:"byma"},
  {s:"SI",n:"Silvergate Bancorp",t:"cedear",m:"byma"},
  {s:"SID",n:"Companhia Siderúrgica Nacional",t:"cedear",m:"byma"},
  {s:"SIEGY",n:"Siemens Ag Adr",t:"cedear",m:"byma"},
  {s:"SKHY",n:"SK HYNIX INC",t:"cedear",m:"byma"},
  {s:"SLB",n:"Schlumberger Ltd",t:"cedear",m:"byma"},
  {s:"SLV",n:"iShares SILVER TRUST",t:"cedear",m:"byma"},
  {s:"SMH",n:"VAN ECK SEMICONDUCTOR ETF",t:"cedear",m:"byma"},
  {s:"SMSN",n:"Samsung Electronics Co. Ltd.",t:"cedear",m:"byma"},
  {s:"SNA",n:"Snap-On Inc",t:"cedear",m:"byma"},
  {s:"SNAP",n:"Snap Inc.",t:"cedear",m:"byma"},
  {s:"SNDK",n:"Sandisk Corporation",t:"cedear",m:"byma"},
  {s:"SNOW",n:"Snowflake Inc.",t:"cedear",m:"byma"},
  {s:"SNP",n:"China Petroleum & Chem",t:"cedear",m:"byma"},
  {s:"SONY",n:"Sony Group Corporation",t:"cedear",m:"byma"},
  {s:"SOYB",n:"Teucrium Soybean Fund",t:"cedear",m:"byma"},
  {s:"SPCE",n:"Virgin Galactic",t:"cedear",m:"byma"},
  {s:"SPCX",n:"SPACE EXPLORATION TECHNOLOGIES CORP.",t:"cedear",m:"byma"},
  {s:"SPGI",n:"S&P Global Inc",t:"cedear",m:"byma"},
  {s:"SPHQ",n:"Invesco S&P 500 quality ETF",t:"cedear",m:"byma"},
  {s:"SPOT",n:"Spotify Technology S.A.",t:"cedear",m:"byma"},
  {s:"SPXL",n:"DIREXION DAILY S&P 500 BULL 3X",t:"cedear",m:"byma"},
  {s:"SPY",n:"SPDR S&P 500",t:"cedear",m:"byma"},
  {s:"STLA",n:"Stellantis",t:"cedear",m:"byma"},
  {s:"STNE",n:"StoneCo Ltd",t:"cedear",m:"byma"},
  {s:"SUZ",n:"Suzano Papel E Celulose S.A.",t:"cedear",m:"byma"},
  {s:"SUZB3",n:"Suzano S.A.",t:"cedear",m:"byma"},
  {s:"SWKS",n:"Skyworks Solutions",t:"cedear",m:"byma"},
  {s:"SYY",n:"Sysco Corp.",t:"cedear",m:"byma"},
  {s:"T",n:"At &T Inc.",t:"cedear",m:"byma"},
  {s:"TCOM",n:"TRIP.COM Group Ltd.",t:"cedear",m:"byma"},
  {s:"TEAM",n:"ATLASSIAN CORPORATION",t:"cedear",m:"byma"},
  {s:"TEM",n:"TEMPUS AI INC",t:"cedear",m:"byma"},
  {s:"TEN",n:"Tenaris",t:"cedear",m:"byma"},
  {s:"TGT",n:"Target Corporation",t:"cedear",m:"byma"},
  {s:"TIIAY",n:"Telecom Italia S.P.A. Ordinary Shares",t:"cedear",m:"byma"},
  {s:"TIMB",n:"Tim Participações S.A.",t:"cedear",m:"byma"},
  {s:"TIMS3",n:"TIM S.A.",t:"cedear",m:"byma"},
  {s:"TJX",n:"TJX Companies Inc/The",t:"cedear",m:"byma"},
  {s:"TLN",n:"TALEN ENERGY CORP",t:"cedear",m:"byma"},
  {s:"TM",n:"Toyota Motor Corporation",t:"cedear",m:"byma"},
  {s:"TMO",n:"Thermo Fisher Scientific Inc.",t:"cedear",m:"byma"},
  {s:"TMUS",n:"T-mobile",t:"cedear",m:"byma"},
  {s:"TQQQ",n:"ProShares UltraPro QQQ",t:"cedear",m:"byma"},
  {s:"TRIP",n:"Tripadvisor, Inc.",t:"cedear",m:"byma"},
  {s:"TRVV",n:"The Travelers Cos. Inc.",t:"cedear",m:"byma"},
  {s:"TSLA",n:"Tesla, Inc.",t:"cedear",m:"byma"},
  {s:"TSM",n:"Taiwan Semiconductor Manufacturing",t:"cedear",m:"byma"},
  {s:"TTE",n:"TotalEnergies SE",t:"cedear",m:"byma"},
  {s:"TTM",n:"Tata Motors Ltd",t:"cedear",m:"byma"},
  {s:"TV",n:"Grupo Televisa S.A.",t:"cedear",m:"byma"},
  {s:"TWLO",n:"Twilio Inc",t:"cedear",m:"byma"},
  {s:"TWTR",n:"Twitter, Inc.",t:"cedear",m:"byma"},
  {s:"TXN",n:"Texas Instruments Inc",t:"cedear",m:"byma"},
  {s:"TXR",n:"Ternium S.A.",t:"cedear",m:"byma"},
  {s:"UAL",n:"United Airlines Holdings Inc.",t:"cedear",m:"byma"},
  {s:"UBER",n:"Uber Technologies Inc.",t:"cedear",m:"byma"},
  {s:"UGP",n:"Ultrapar Participações S.A.",t:"cedear",m:"byma"},
  {s:"UL",n:"Unilever PLC - Sponsored",t:"cedear",m:"byma"},
  {s:"UN",n:"NU Holdings Ltd/Cayman Islands",t:"cedear",m:"byma"},
  {s:"UNH",n:"UnitedHealth Group Inc.",t:"cedear",m:"byma"},
  {s:"UNP",n:"Union Pacific Corp.",t:"cedear",m:"byma"},
  {s:"UPST",n:"Upstart Hldgs Inc",t:"cedear",m:"byma"},
  {s:"URA",n:"Global X Uranium ETF",t:"cedear",m:"byma"},
  {s:"URBN",n:"Urban Outfitters INC.",t:"cedear",m:"byma"},
  {s:"USB",n:"U.S. Bancorp",t:"cedear",m:"byma"},
  {s:"USO",n:"United States Oil Fund",t:"cedear",m:"byma"},
  {s:"V",n:"Visa Inc",t:"cedear",m:"byma"},
  {s:"VALE",n:"Vale S.A.",t:"cedear",m:"byma"},
  {s:"VALE3",n:"Vale S.A.",t:"cedear",m:"byma"},
  {s:"VEA",n:"Vanguard FTSE Developed Markets ETF",t:"cedear",m:"byma"},
  {s:"VIG",n:"VANGUARD DIVIDEND APPRECIATION",t:"cedear",m:"byma"},
  {s:"VIST",n:"Vista Energy S.A.B. de C.V.",t:"cedear",m:"byma"},
  {s:"VIV",n:"Telefônica Brasil S.A.",t:"cedear",m:"byma"},
  {s:"VIVT3",n:"Telefônica Brasil S.A.",t:"cedear",m:"byma"},
  {s:"VOD",n:"Vodafone Group Plc",t:"cedear",m:"byma"},
  {s:"VRSN",n:"Verisign, Inc.",t:"cedear",m:"byma"},
  {s:"VRTX",n:"VERTEX PHARMACEUTICALS INC",t:"cedear",m:"byma"},
  {s:"VST",n:"VISTRA CORPORATION",t:"cedear",m:"byma"},
  {s:"VXX",n:"iPath Series B S&P 500 VIX",t:"cedear",m:"byma"},
  {s:"VZ",n:"Verizon Communications Inc.",t:"cedear",m:"byma"},
  {s:"WBA",n:"Walgreens Boots Alliance Inc.",t:"cedear",m:"byma"},
  {s:"WBO",n:"Weibo Corporation",t:"cedear",m:"byma"},
  {s:"WDC",n:"WESTERN DIGITAL CORP",t:"cedear",m:"byma"},
  {s:"WEGE3",n:"Weg S.A.",t:"cedear",m:"byma"},
  {s:"WELL",n:"WELLTOWER INC",t:"cedear",m:"byma"},
  {s:"WFC",n:"Wells Fargo & Co.",t:"cedear",m:"byma"},
  {s:"WMT",n:"Walmart Inc.",t:"cedear",m:"byma"},
  {s:"XLB",n:"The Materials Select Sector SPDR Fund",t:"cedear",m:"byma"},
  {s:"XLC",n:"The Communication Services Select Sector SPDR Fund",t:"cedear",m:"byma"},
  {s:"XLE",n:"ENERGY SELECT SECTOR SPDR FUND",t:"cedear",m:"byma"},
  {s:"XLF",n:"FINANCIAL SELECT SECTOR SPDR FUND",t:"cedear",m:"byma"},
  {s:"XLI",n:"The Industrial Select Sector SPDR Fund",t:"cedear",m:"byma"},
  {s:"XLK",n:"The Technology Select Sector SPDR Fund",t:"cedear",m:"byma"},
  {s:"XLP",n:"The Consumer Staples Select Sector SPDR Fund",t:"cedear",m:"byma"},
  {s:"XLRE",n:"The Real Estate Select Sector SPDR Fund",t:"cedear",m:"byma"},
  {s:"XLU",n:"Utilities Select Sector SPDR Fund",t:"cedear",m:"byma"},
  {s:"XLV",n:"The Health Care Select Sector SPDR Fund",t:"cedear",m:"byma"},
  {s:"XLY",n:"The Consumer Discretionary Select Sector SPDR Fund",t:"cedear",m:"byma"},
  {s:"XME",n:"State Street SPDR S&P Metals & Mining ETF",t:"cedear",m:"byma"},
  {s:"XOM",n:"Exxon Mobil Corporation",t:"cedear",m:"byma"},
  {s:"XP",n:"XP Inc",t:"cedear",m:"byma"},
  {s:"XPEV",n:"XPENG INC",t:"cedear",m:"byma"},
  {s:"XROX",n:"Xerox Holding Corporation",t:"cedear",m:"byma"},
  {s:"XYZ",n:"Square Inc.",t:"cedear",m:"byma"},
  {s:"YELP",n:"Yelp Inc.",t:"cedear",m:"byma"},
  {s:"YZCA",n:"Yanzhou Coal Mining Co. Ltd.",t:"cedear",m:"byma"},
  {s:"ZM",n:"Zoom Video Communications Inc.",t:"cedear",m:"byma"},
  {s:"AGRO",n:"Agrometal",t:"accion_ar",m:"byma"},
  {s:"ALUA",n:"Aluar",t:"accion_ar",m:"byma"},
  {s:"AUSO",n:"Autopistas del Sol",t:"accion_ar",m:"byma"},
  {s:"BBAR",n:"BBVA Argentina",t:"accion_ar",m:"byma"},
  {s:"BHIP",n:"Banco Hipotecario",t:"accion_ar",m:"byma"},
  {s:"BMA",n:"Banco Macro",t:"accion_ar",m:"byma"},
  {s:"BOLT",n:"Boldt",t:"accion_ar",m:"byma"},
  {s:"BPAT",n:"Banco Patagonia",t:"accion_ar",m:"byma"},
  {s:"BYMA",n:"Bolsas y Mercados Argentinos",t:"accion_ar",m:"byma"},
  {s:"CADO",n:"Carlos Casado S.A.",t:"accion_ar",m:"byma"},
  {s:"CAPX",n:"Capex S.A.",t:"accion_ar",m:"byma"},
  {s:"CARC",n:"Carboclor",t:"accion_ar",m:"byma"},
  {s:"CECO2",n:"Central térmica Costanera",t:"accion_ar",m:"byma"},
  {s:"CELU",n:"Celulosa",t:"accion_ar",m:"byma"},
  {s:"CEPU",n:"Central Puerto",t:"accion_ar",m:"byma"},
  {s:"CGPA2",n:"Camuzzi Gas Pampeana",t:"accion_ar",m:"byma"},
  {s:"COME",n:"Sociedad Comercial del Plata",t:"accion_ar",m:"byma"},
  {s:"CRES",n:"Cresud",t:"accion_ar",m:"byma"},
  {s:"CTIO",n:"Consultatio",t:"accion_ar",m:"byma"},
  {s:"CVH",n:"Flow",t:"accion_ar",m:"byma"},
  {s:"DGCU2",n:"Distribuidora de Gas Cuyana",t:"accion_ar",m:"byma"},
  {s:"DOME",n:"Domec S.A.",t:"accion_ar",m:"byma"},
  {s:"EDN",n:"Edenor",t:"accion_ar",m:"byma"},
  {s:"FERR",n:"Ferrum",t:"accion_ar",m:"byma"},
  {s:"FIPL",n:"Fiplasto",t:"accion_ar",m:"byma"},
  {s:"GAMI",n:"B-Gaming",t:"accion_ar",m:"byma"},
  {s:"GARO",n:"Garovaglio & Zorraquín",t:"accion_ar",m:"byma"},
  {s:"GBAN",n:"Naturgy Ban",t:"accion_ar",m:"byma"},
  {s:"GCLA",n:"Grupo Clarín",t:"accion_ar",m:"byma"},
  {s:"GGAL",n:"Grupo Financiero Galicia",t:"accion_ar",m:"byma"},
  {s:"GRIM",n:"Grimoldi",t:"accion_ar",m:"byma"},
  {s:"HARG",n:"Holcim Argentina",t:"accion_ar",m:"byma"},
  {s:"HAVA",n:"Havanna",t:"accion_ar",m:"byma"},
  {s:"INTR",n:"Compañía Introductora de Buenos Aires",t:"accion_ar",m:"byma"},
  {s:"INVJ",n:"Inversora Juramento",t:"accion_ar",m:"byma"},
  {s:"LEDE",n:"Grupo Ledesma",t:"accion_ar",m:"byma"},
  {s:"LOMA",n:"Loma Negra",t:"accion_ar",m:"byma"},
  {s:"LONG",n:"Longvie",t:"accion_ar",m:"byma"},
  {s:"MIRG",n:"Mirgor",t:"accion_ar",m:"byma"},
  {s:"MOLA",n:"Molinos Agro",t:"accion_ar",m:"byma"},
  {s:"MOLI",n:"Molinos Río de la Plata",t:"accion_ar",m:"byma"},
  {s:"MORI",n:"Morixe Hermanos S.A.C.I.",t:"accion_ar",m:"byma"},
  {s:"OEST",n:"Grupo Concesionario del Oeste",t:"accion_ar",m:"byma"},
  {s:"PAMP",n:"Pampa Energía",t:"accion_ar",m:"byma"},
  {s:"PATA",n:"La Anónima",t:"accion_ar",m:"byma"},
  {s:"POLL",n:"Polledo",t:"accion_ar",m:"byma"},
  {s:"RICH",n:"Laboratorios Richmond",t:"accion_ar",m:"byma"},
  {s:"ROSE",n:"Instituto Rosenbusch",t:"accion_ar",m:"byma"},
  {s:"SAMI",n:"San Miguel S.A.",t:"accion_ar",m:"byma"},
  {s:"SEMI",n:"Molinos Juan Semino",t:"accion_ar",m:"byma"},
  {s:"SUPV",n:"Grupo Supervielle",t:"accion_ar",m:"byma"},
  {s:"TECO2",n:"Telecom Argentina",t:"accion_ar",m:"byma"},
  {s:"TGNO4",n:"Transportadora de Gas del Norte",t:"accion_ar",m:"byma"},
  {s:"TGSU2",n:"Transportadora de Gas del Sur",t:"accion_ar",m:"byma"},
  {s:"TRAN",n:"Transener",t:"accion_ar",m:"byma"},
  {s:"TXAR",n:"Ternium",t:"accion_ar",m:"byma"},
  {s:"VALO",n:"Banco de Valores",t:"accion_ar",m:"byma"},
  {s:"YPFD",n:"YPF",t:"accion_ar",m:"byma"},
  {s:"AE38",n:"Bonar 2038 (AE38) · ley argentina · en pesos",t:"bono",m:"byma"},
  {s:"AE38C",n:"Bonar 2038 (AE38) · ley argentina · dólar cable",t:"bono",m:"byma"},
  {s:"AE38D",n:"Bonar 2038 (AE38) · ley argentina · dólar MEP",t:"bono",m:"byma"},
  {s:"AL29",n:"Bonar 2029 (AL29) · ley argentina · en pesos",t:"bono",m:"byma"},
  {s:"AL29C",n:"Bonar 2029 (AL29) · ley argentina · dólar cable",t:"bono",m:"byma"},
  {s:"AL29D",n:"Bonar 2029 (AL29) · ley argentina · dólar MEP",t:"bono",m:"byma"},
  {s:"AL30",n:"Bonar 2030 (AL30) · ley argentina · en pesos",t:"bono",m:"byma"},
  {s:"AL30C",n:"Bonar 2030 (AL30) · ley argentina · dólar cable",t:"bono",m:"byma"},
  {s:"AL30D",n:"Bonar 2030 (AL30) · ley argentina · dólar MEP",t:"bono",m:"byma"},
  {s:"AL35",n:"Bonar 2035 (AL35) · ley argentina · en pesos",t:"bono",m:"byma"},
  {s:"AL35C",n:"Bonar 2035 (AL35) · ley argentina · dólar cable",t:"bono",m:"byma"},
  {s:"AL35D",n:"Bonar 2035 (AL35) · ley argentina · dólar MEP",t:"bono",m:"byma"},
  {s:"AL41",n:"Bonar 2041 (AL41) · ley argentina · en pesos",t:"bono",m:"byma"},
  {s:"AL41C",n:"Bonar 2041 (AL41) · ley argentina · dólar cable",t:"bono",m:"byma"},
  {s:"AL41D",n:"Bonar 2041 (AL41) · ley argentina · dólar MEP",t:"bono",m:"byma"},
  {s:"AN29",n:"Bono soberano 2029 (AN29) · ley argentina · en pesos",t:"bono",m:"byma"},
  {s:"AN29C",n:"Bono soberano 2029 (AN29) · ley argentina · dólar cable",t:"bono",m:"byma"},
  {s:"AN29D",n:"Bono soberano 2029 (AN29) · ley argentina · dólar MEP",t:"bono",m:"byma"},
  {s:"AO27",n:"Bono soberano 2027 (AO27) · ley argentina · en pesos",t:"bono",m:"byma"},
  {s:"AO27C",n:"Bono soberano 2027 (AO27) · ley argentina · dólar cable",t:"bono",m:"byma"},
  {s:"AO27D",n:"Bono soberano 2027 (AO27) · ley argentina · dólar MEP",t:"bono",m:"byma"},
  {s:"AO28",n:"Bono soberano 2028 (AO28) · ley argentina · en pesos",t:"bono",m:"byma"},
  {s:"AO28C",n:"Bono soberano 2028 (AO28) · ley argentina · dólar cable",t:"bono",m:"byma"},
  {s:"AO28D",n:"Bono soberano 2028 (AO28) · ley argentina · dólar MEP",t:"bono",m:"byma"},
  {s:"AO29",n:"Bono soberano 2029 (AO29) · ley argentina · en pesos",t:"bono",m:"byma"},
  {s:"AO29C",n:"Bono soberano 2029 (AO29) · ley argentina · dólar cable",t:"bono",m:"byma"},
  {s:"AO29D",n:"Bono soberano 2029 (AO29) · ley argentina · dólar MEP",t:"bono",m:"byma"},
  {s:"BA37D",n:"Provincia de Buenos Aires 2037 (BA37D) · dólares",t:"bono",m:"byma"},
  {s:"BA7DC",n:"Renta fija BYMA · panel de bonos (BA7DC)",t:"bono",m:"byma"},
  {s:"BA7DD",n:"Renta fija BYMA · panel de bonos (BA7DD)",t:"bono",m:"byma"},
  {s:"BAF27",n:"Renta fija BYMA · panel de bonos (BAF27)",t:"bono",m:"byma"},
  {s:"BAM27",n:"Renta fija BYMA · panel de bonos (BAM27)",t:"bono",m:"byma"},
  {s:"BAO27",n:"Renta fija BYMA · panel de bonos (BAO27)",t:"bono",m:"byma"},
  {s:"BB37D",n:"Provincia de Buenos Aires 2037 (BB37D) · dólares",t:"bono",m:"byma"},
  {s:"BB7DC",n:"Renta fija BYMA · panel de bonos (BB7DC)",t:"bono",m:"byma"},
  {s:"BB7DD",n:"Renta fija BYMA · panel de bonos (BB7DD)",t:"bono",m:"byma"},
  {s:"BC33C",n:"Renta fija BYMA · panel de bonos (BC33C)",t:"bono",m:"byma"},
  {s:"BC33D",n:"Renta fija BYMA · panel de bonos (BC33D)",t:"bono",m:"byma"},
  {s:"BC37D",n:"Provincia de Buenos Aires 2037 (BC37D) · dólares",t:"bono",m:"byma"},
  {s:"BC7DC",n:"Renta fija BYMA · panel de bonos (BC7DC)",t:"bono",m:"byma"},
  {s:"BC7DD",n:"Renta fija BYMA · panel de bonos (BC7DD)",t:"bono",m:"byma"},
  {s:"BCIUO",n:"Renta fija BYMA · panel de bonos (BCIUO)",t:"bono",m:"byma"},
  {s:"BDC28",n:"Ciudad de Buenos Aires 2028 (BDC28)",t:"bono",m:"byma"},
  {s:"BDC33",n:"Ciudad de Buenos Aires 2033 (BDC33)",t:"bono",m:"byma"},
  {s:"BDC36",n:"Ciudad de Buenos Aires 2036 (BDC36)",t:"bono",m:"byma"},
  {s:"BGD26",n:"Renta fija BYMA · panel de bonos (BGD26)",t:"bono",m:"byma"},
  {s:"BLE27",n:"Renta fija BYMA · panel de bonos (BLE27)",t:"bono",m:"byma"},
  {s:"BPA7C",n:"Bopreal del BCRA (BPA7) · dólar cable · vence 31/10/2027",t:"bono",m:"byma"},
  {s:"BPA7D",n:"Bopreal del BCRA (BPA7) · dólar MEP · vence 31/10/2027",t:"bono",m:"byma"},
  {s:"BPA8C",n:"Bopreal del BCRA (BPA8) · dólar cable",t:"bono",m:"byma"},
  {s:"BPA8D",n:"Bopreal del BCRA (BPA8) · dólar MEP",t:"bono",m:"byma"},
  {s:"BPB7C",n:"Bopreal del BCRA (BPB7) · dólar cable · vence 31/10/2027",t:"bono",m:"byma"},
  {s:"BPB7D",n:"Bopreal del BCRA (BPB7) · dólar MEP · vence 31/10/2027",t:"bono",m:"byma"},
  {s:"BPB8C",n:"Bopreal del BCRA (BPB8) · dólar cable",t:"bono",m:"byma"},
  {s:"BPB8D",n:"Bopreal del BCRA (BPB8) · dólar MEP",t:"bono",m:"byma"},
  {s:"BPC7C",n:"Bopreal del BCRA (BPC7) · dólar cable · vence 31/10/2027",t:"bono",m:"byma"},
  {s:"BPC7D",n:"Bopreal del BCRA (BPC7) · dólar MEP · vence 31/10/2027",t:"bono",m:"byma"},
  {s:"BPD7C",n:"Bopreal del BCRA (BPD7) · dólar cable · vence 31/10/2027",t:"bono",m:"byma"},
  {s:"BPD7D",n:"Bopreal del BCRA (BPD7) · dólar MEP · vence 31/10/2027",t:"bono",m:"byma"},
  {s:"BPOA7",n:"Bopreal del BCRA (BPOA7) · en pesos",t:"bono",m:"byma"},
  {s:"BPOA8",n:"Bopreal del BCRA (BPOA8) · en pesos",t:"bono",m:"byma"},
  {s:"BPOB7",n:"Bopreal del BCRA (BPOB7) · en pesos",t:"bono",m:"byma"},
  {s:"BPOB8",n:"Bopreal del BCRA (BPOB8) · en pesos",t:"bono",m:"byma"},
  {s:"BPOC7",n:"Bopreal del BCRA (BPOC7) · en pesos",t:"bono",m:"byma"},
  {s:"BPOD7",n:"Bopreal del BCRA (BPOD7) · en pesos",t:"bono",m:"byma"},
  {s:"BU3S6",n:"Renta fija BYMA · panel de bonos (BU3S6)",t:"bono",m:"byma"},
  {s:"BU4N6",n:"Renta fija BYMA · panel de bonos (BU4N6)",t:"bono",m:"byma"},
  {s:"CARP",n:"Renta fija BYMA · panel de bonos (CARP)",t:"bono",m:"byma"},
  {s:"CO26",n:"Provincia de Córdoba 2026 (CO26)",t:"bono",m:"byma"},
  {s:"CO26D",n:"Provincia de Córdoba 2026 (CO26D) · dólar MEP",t:"bono",m:"byma"},
  {s:"CO2D7",n:"Renta fija BYMA · panel de bonos (CO2D7)",t:"bono",m:"byma"},
  {s:"CO32",n:"Provincia de Córdoba 2032 (CO32)",t:"bono",m:"byma"},
  {s:"CO32C",n:"Provincia de Córdoba 2032 (CO32C) · dólar cable",t:"bono",m:"byma"},
  {s:"CO32D",n:"Provincia de Córdoba 2032 (CO32D) · dólar MEP",t:"bono",m:"byma"},
  {s:"CO35",n:"Provincia de Córdoba 2035 (CO35)",t:"bono",m:"byma"},
  {s:"CO35C",n:"Provincia de Córdoba 2035 (CO35C) · dólar cable",t:"bono",m:"byma"},
  {s:"CO35D",n:"Provincia de Córdoba 2035 (CO35D) · dólar MEP",t:"bono",m:"byma"},
  {s:"CO3D7",n:"Renta fija BYMA · panel de bonos (CO3D7)",t:"bono",m:"byma"},
  {s:"COD7",n:"Renta fija BYMA · panel de bonos (COD7)",t:"bono",m:"byma"},
  {s:"COY27",n:"Renta fija BYMA · panel de bonos (COY27)",t:"bono",m:"byma"},
  {s:"CUAP",n:"Cuasipar en pesos ajustado por CER (CUAP) · vence 31/12/2045",t:"bono",m:"byma"},
  {s:"CUAPD",n:"Cuasipar en pesos ajustado por CER (CUAPD)",t:"bono",m:"byma"},
  {s:"D10Y7",n:"Letra del Tesoro dólar linked (D10Y7)",t:"letra",m:"byma"},
  {s:"D15E7",n:"Letra del Tesoro dólar linked (D15E7)",t:"letra",m:"byma"},
  {s:"D30N6",n:"Letra del Tesoro dólar linked (D30N6)",t:"letra",m:"byma"},
  {s:"D30O6",n:"Letra del Tesoro dólar linked (D30O6)",t:"letra",m:"byma"},
  {s:"D30S6",n:"Letra del Tesoro dólar linked (D30S6)",t:"letra",m:"byma"},
  {s:"D31G6",n:"Letra del Tesoro dólar linked (D31G6)",t:"letra",m:"byma"},
  {s:"D31M7",n:"Letra del Tesoro dólar linked (D31M7)",t:"letra",m:"byma"},
  {s:"DICP",n:"Discount en pesos ajustado por CER (DICP) · vence 31/12/2033",t:"bono",m:"byma"},
  {s:"DICPC",n:"Discount en pesos ajustado por CER (DICPC)",t:"bono",m:"byma"},
  {s:"DICPD",n:"Discount en pesos ajustado por CER (DICPD)",t:"bono",m:"byma"},
  {s:"DIP0",n:"Discount en pesos ajustado por CER (DIP0)",t:"bono",m:"byma"},
  {s:"DS6D",n:"Renta fija BYMA · panel de bonos (DS6D)",t:"bono",m:"byma"},
  {s:"EF25D",n:"Renta fija BYMA · panel de bonos (EF25D)",t:"bono",m:"byma"},
  {s:"EM33C",n:"Renta fija BYMA · panel de bonos (EM33C)",t:"bono",m:"byma"},
  {s:"EM33D",n:"Renta fija BYMA · panel de bonos (EM33D)",t:"bono",m:"byma"},
  {s:"ERE27",n:"Renta fija BYMA · panel de bonos (ERE27)",t:"bono",m:"byma"},
  {s:"ERF25",n:"Renta fija BYMA · panel de bonos (ERF25)",t:"bono",m:"byma"},
  {s:"ERM33",n:"Renta fija BYMA · panel de bonos (ERM33)",t:"bono",m:"byma"},
  {s:"GD29",n:"Global 2029 (GD29) · ley Nueva York · en pesos",t:"bono",m:"byma"},
  {s:"GD29C",n:"Global 2029 (GD29) · ley Nueva York · dólar cable",t:"bono",m:"byma"},
  {s:"GD29D",n:"Global 2029 (GD29) · ley Nueva York · dólar MEP",t:"bono",m:"byma"},
  {s:"GD30",n:"Global 2030 (GD30) · ley Nueva York · en pesos",t:"bono",m:"byma"},
  {s:"GD30C",n:"Global 2030 (GD30) · ley Nueva York · dólar cable",t:"bono",m:"byma"},
  {s:"GD30D",n:"Global 2030 (GD30) · ley Nueva York · dólar MEP",t:"bono",m:"byma"},
  {s:"GD35",n:"Global 2035 (GD35) · ley Nueva York · en pesos",t:"bono",m:"byma"},
  {s:"GD35C",n:"Global 2035 (GD35) · ley Nueva York · dólar cable",t:"bono",m:"byma"},
  {s:"GD35D",n:"Global 2035 (GD35) · ley Nueva York · dólar MEP",t:"bono",m:"byma"},
  {s:"GD38",n:"Global 2038 (GD38) · ley Nueva York · en pesos",t:"bono",m:"byma"},
  {s:"GD38C",n:"Global 2038 (GD38) · ley Nueva York · dólar cable",t:"bono",m:"byma"},
  {s:"GD38D",n:"Global 2038 (GD38) · ley Nueva York · dólar MEP",t:"bono",m:"byma"},
  {s:"GD41",n:"Global 2041 (GD41) · ley Nueva York · en pesos",t:"bono",m:"byma"},
  {s:"GD41C",n:"Global 2041 (GD41) · ley Nueva York · dólar cable",t:"bono",m:"byma"},
  {s:"GD41D",n:"Global 2041 (GD41) · ley Nueva York · dólar MEP",t:"bono",m:"byma"},
  {s:"GD46",n:"Global 2046 (GD46) · ley Nueva York · en pesos",t:"bono",m:"byma"},
  {s:"GD46C",n:"Global 2046 (GD46) · ley Nueva York · dólar cable",t:"bono",m:"byma"},
  {s:"GD46D",n:"Global 2046 (GD46) · ley Nueva York · dólar MEP",t:"bono",m:"byma"},
  {s:"ISG29",n:"Renta fija BYMA · panel de bonos (ISG29)",t:"bono",m:"byma"},
  {s:"LK01Q",n:"Renta fija BYMA · panel de bonos (LK01Q)",t:"bono",m:"byma"},
  {s:"LK1QD",n:"Renta fija BYMA · panel de bonos (LK1QD)",t:"bono",m:"byma"},
  {s:"NDG34",n:"Renta fija BYMA · panel de bonos (NDG34)",t:"bono",m:"byma"},
  {s:"NDG4C",n:"Renta fija BYMA · panel de bonos (NDG4C)",t:"bono",m:"byma"},
  {s:"NDG4D",n:"Renta fija BYMA · panel de bonos (NDG4D)",t:"bono",m:"byma"},
  {s:"NDT25",n:"Renta fija BYMA · panel de bonos (NDT25)",t:"bono",m:"byma"},
  {s:"NDT5C",n:"Renta fija BYMA · panel de bonos (NDT5C)",t:"bono",m:"byma"},
  {s:"NDT5D",n:"Renta fija BYMA · panel de bonos (NDT5D)",t:"bono",m:"byma"},
  {s:"PAP0",n:"Par (PAP0)",t:"bono",m:"byma"},
  {s:"PARP",n:"Par (PARP) · vence 31/12/2038",t:"bono",m:"byma"},
  {s:"PAY0D",n:"Par (PAY0D)",t:"bono",m:"byma"},
  {s:"PBA27",n:"Renta fija BYMA · panel de bonos (PBA27)",t:"bono",m:"byma"},
  {s:"PBA28",n:"Renta fija BYMA · panel de bonos (PBA28)",t:"bono",m:"byma"},
  {s:"PM29C",n:"Renta fija BYMA · panel de bonos (PM29C)",t:"bono",m:"byma"},
  {s:"PM29D",n:"Renta fija BYMA · panel de bonos (PM29D)",t:"bono",m:"byma"},
  {s:"PMA28",n:"Renta fija BYMA · panel de bonos (PMA28)",t:"bono",m:"byma"},
  {s:"PMD26",n:"Renta fija BYMA · panel de bonos (PMD26)",t:"bono",m:"byma"},
  {s:"PMM29",n:"Renta fija BYMA · panel de bonos (PMM29)",t:"bono",m:"byma"},
  {s:"PR17",n:"Renta fija BYMA · panel de bonos (PR17)",t:"bono",m:"byma"},
  {s:"PUA36",n:"Renta fija BYMA · panel de bonos (PUA36)",t:"bono",m:"byma"},
  {s:"PUA6C",n:"Renta fija BYMA · panel de bonos (PUA6C)",t:"bono",m:"byma"},
  {s:"PUA6D",n:"Renta fija BYMA · panel de bonos (PUA6D)",t:"bono",m:"byma"},
  {s:"S13N6",n:"Lecap · letra del Tesoro a tasa fija (S13N6) · vence 13/11/2026",t:"letra",m:"byma"},
  {s:"S15S6",n:"Lecap · letra del Tesoro a tasa fija (S15S6)",t:"letra",m:"byma"},
  {s:"S16O6",n:"Lecap · letra del Tesoro a tasa fija (S16O6) · vence 16/10/2026",t:"letra",m:"byma"},
  {s:"S24DC",n:"Renta fija BYMA · panel de bonos (S24DC)",t:"bono",m:"byma"},
  {s:"S24DD",n:"Renta fija BYMA · panel de bonos (S24DD)",t:"bono",m:"byma"},
  {s:"S29E7",n:"Lecap · letra del Tesoro a tasa fija (S29E7) · vence 29/01/2027",t:"letra",m:"byma"},
  {s:"S2N6D",n:"Renta fija BYMA · panel de bonos (S2N6D)",t:"bono",m:"byma"},
  {s:"S2O6D",n:"Renta fija BYMA · panel de bonos (S2O6D)",t:"bono",m:"byma"},
  {s:"S2S6C",n:"Renta fija BYMA · panel de bonos (S2S6C)",t:"bono",m:"byma"},
  {s:"S2S6D",n:"Renta fija BYMA · panel de bonos (S2S6D)",t:"bono",m:"byma"},
  {s:"S30N6",n:"Lecap · letra del Tesoro a tasa fija (S30N6) · vence 30/11/2026",t:"letra",m:"byma"},
  {s:"S30O6",n:"Lecap · letra del Tesoro a tasa fija (S30O6) · vence 30/10/2026",t:"letra",m:"byma"},
  {s:"S30S6",n:"Lecap · letra del Tesoro a tasa fija (S30S6) · vence 30/09/2026",t:"letra",m:"byma"},
  {s:"SA24D",n:"Renta fija BYMA · panel de bonos (SA24D)",t:"bono",m:"byma"},
  {s:"SFD34",n:"Renta fija BYMA · panel de bonos (SFD34)",t:"bono",m:"byma"},
  {s:"SFD4C",n:"Renta fija BYMA · panel de bonos (SFD4C)",t:"bono",m:"byma"},
  {s:"SFD4D",n:"Renta fija BYMA · panel de bonos (SFD4D)",t:"bono",m:"byma"},
  {s:"SFN27",n:"Renta fija BYMA · panel de bonos (SFN27)",t:"bono",m:"byma"},
  {s:"SN6D",n:"Renta fija BYMA · panel de bonos (SN6D)",t:"bono",m:"byma"},
  {s:"SS6C",n:"Renta fija BYMA · panel de bonos (SS6C)",t:"bono",m:"byma"},
  {s:"SS6D",n:"Renta fija BYMA · panel de bonos (SS6D)",t:"bono",m:"byma"},
  {s:"T15E7",n:"Bono del Tesoro a tasa fija (T15E7) · vence 15/01/2027",t:"bono",m:"byma"},
  {s:"T30A7",n:"Bono del Tesoro a tasa fija (T30A7) · vence 30/04/2027",t:"bono",m:"byma"},
  {s:"T30J7",n:"Bono del Tesoro a tasa fija (T30J7) · vence 30/06/2027",t:"bono",m:"byma"},
  {s:"T31Y7",n:"Bono del Tesoro a tasa fija (T31Y7) · vence 31/05/2027",t:"bono",m:"byma"},
  {s:"TA7C",n:"Renta fija BYMA · panel de bonos (TA7C)",t:"bono",m:"byma"},
  {s:"TA7D",n:"Renta fija BYMA · panel de bonos (TA7D)",t:"bono",m:"byma"},
  {s:"TJ7D",n:"Renta fija BYMA · panel de bonos (TJ7D)",t:"bono",m:"byma"},
  {s:"TMF27",n:"Renta fija BYMA · panel de bonos (TMF27)",t:"bono",m:"byma"},
  {s:"TMF28",n:"Renta fija BYMA · panel de bonos (TMF28)",t:"bono",m:"byma"},
  {s:"TMF7D",n:"Renta fija BYMA · panel de bonos (TMF7D)",t:"bono",m:"byma"},
  {s:"TMF8D",n:"Renta fija BYMA · panel de bonos (TMF8D)",t:"bono",m:"byma"},
  {s:"TMG27",n:"Renta fija BYMA · panel de bonos (TMG27)",t:"bono",m:"byma"},
  {s:"TMG28",n:"Renta fija BYMA · panel de bonos (TMG28)",t:"bono",m:"byma"},
  {s:"TML27",n:"Renta fija BYMA · panel de bonos (TML27)",t:"bono",m:"byma"},
  {s:"TMVE8",n:"Renta fija BYMA · panel de bonos (TMVE8)",t:"bono",m:"byma"},
  {s:"TO26",n:"Bonte 2026 · bono del Tesoro en pesos a tasa fija (TO26)",t:"bono",m:"byma"},
  {s:"TO26C",n:"Bonte 2026 · bono del Tesoro a tasa fija (TO26C)",t:"bono",m:"byma"},
  {s:"TO26D",n:"Bonte 2026 · bono del Tesoro a tasa fija (TO26D)",t:"bono",m:"byma"},
  {s:"TTD26",n:"Renta fija BYMA · panel de bonos (TTD26)",t:"bono",m:"byma"},
  {s:"TTD6D",n:"Renta fija BYMA · panel de bonos (TTD6D)",t:"bono",m:"byma"},
  {s:"TVPA",n:"Cupón ligado al PBI (TVPA) · dólares, ley argentina",t:"bono",m:"byma"},
  {s:"TVPE",n:"Cupón ligado al PBI (TVPE) · euros",t:"bono",m:"byma"},
  {s:"TVPP",n:"Cupón ligado al PBI (TVPP) · pesos",t:"bono",m:"byma"},
  {s:"TVPY",n:"Cupón ligado al PBI (TVPY) · dólares, ley Nueva York",t:"bono",m:"byma"},
  {s:"TVPYD",n:"Cupón ligado al PBI (TVPYD) · dólares, ley Nueva York · MEP",t:"bono",m:"byma"},
  {s:"TX26",n:"Boncer · bono del Tesoro ajustado por CER (TX26) · vence 09/11/2026",t:"bono",m:"byma"},
  {s:"TX26D",n:"Boncer · bono del Tesoro ajustado por CER (TX26D)",t:"bono",m:"byma"},
  {s:"TX28",n:"Boncer · bono del Tesoro ajustado por CER (TX28) · vence 09/11/2028",t:"bono",m:"byma"},
  {s:"TX28D",n:"Boncer · bono del Tesoro ajustado por CER (TX28D)",t:"bono",m:"byma"},
  {s:"TX31",n:"Boncer · bono del Tesoro ajustado por CER (TX31)",t:"bono",m:"byma"},
  {s:"TX31D",n:"Boncer · bono del Tesoro ajustado por CER (TX31D)",t:"bono",m:"byma"},
  {s:"TXA7D",n:"Renta fija BYMA · panel de bonos (TXA7D)",t:"bono",m:"byma"},
  {s:"TXD6C",n:"Renta fija BYMA · panel de bonos (TXD6C)",t:"bono",m:"byma"},
  {s:"TXD6D",n:"Renta fija BYMA · panel de bonos (TXD6D)",t:"bono",m:"byma"},
  {s:"TXD7D",n:"Renta fija BYMA · panel de bonos (TXD7D)",t:"bono",m:"byma"},
  {s:"TXD8D",n:"Renta fija BYMA · panel de bonos (TXD8D)",t:"bono",m:"byma"},
  {s:"TXD9D",n:"Renta fija BYMA · panel de bonos (TXD9D)",t:"bono",m:"byma"},
  {s:"TXJ0D",n:"Renta fija BYMA · panel de bonos (TXJ0D)",t:"bono",m:"byma"},
  {s:"TXM7D",n:"Renta fija BYMA · panel de bonos (TXM7D)",t:"bono",m:"byma"},
  {s:"TXM8D",n:"Renta fija BYMA · panel de bonos (TXM8D)",t:"bono",m:"byma"},
  {s:"TXM9D",n:"Renta fija BYMA · panel de bonos (TXM9D)",t:"bono",m:"byma"},
  {s:"TXMD8",n:"Renta fija BYMA · panel de bonos (TXMD8)",t:"bono",m:"byma"},
  {s:"TXMD9",n:"Renta fija BYMA · panel de bonos (TXMD9)",t:"bono",m:"byma"},
  {s:"TXMJ0",n:"Renta fija BYMA · panel de bonos (TXMJ0)",t:"bono",m:"byma"},
  {s:"TXMJ8",n:"Renta fija BYMA · panel de bonos (TXMJ8)",t:"bono",m:"byma"},
  {s:"TXMJ9",n:"Renta fija BYMA · panel de bonos (TXMJ9)",t:"bono",m:"byma"},
  {s:"TXS7D",n:"Renta fija BYMA · panel de bonos (TXS7D)",t:"bono",m:"byma"},
  {s:"TXS8C",n:"Renta fija BYMA · panel de bonos (TXS8C)",t:"bono",m:"byma"},
  {s:"TXS8D",n:"Renta fija BYMA · panel de bonos (TXS8D)",t:"bono",m:"byma"},
  {s:"TY30D",n:"Renta fija BYMA · panel de bonos (TY30D)",t:"bono",m:"byma"},
  {s:"TY30P",n:"Bonte 2030 · bono del Tesoro en pesos suscripto en dólares (TY30P)",t:"bono",m:"byma"},
  {s:"TY7D",n:"Renta fija BYMA · panel de bonos (TY7D)",t:"bono",m:"byma"},
  {s:"TZV27",n:"Bono del Tesoro dólar linked (TZV27) · vence 30/06/2027",t:"bono",m:"byma"},
  {s:"TZV28",n:"Bono del Tesoro dólar linked (TZV28) · vence 30/06/2028",t:"bono",m:"byma"},
  {s:"TZV7D",n:"Renta fija BYMA · panel de bonos (TZV7D)",t:"bono",m:"byma"},
  {s:"TZVD8",n:"Renta fija BYMA · panel de bonos (TZVD8)",t:"bono",m:"byma"},
  {s:"TZX27",n:"Boncer · bono del Tesoro ajustado por CER (TZX27) · vence 30/06/2027",t:"bono",m:"byma"},
  {s:"TZX28",n:"Boncer · bono del Tesoro ajustado por CER (TZX28) · vence 30/06/2028",t:"bono",m:"byma"},
  {s:"TZX7D",n:"Boncer · bono del Tesoro ajustado por CER (TZX7D)",t:"bono",m:"byma"},
  {s:"TZXA7",n:"Boncer · bono del Tesoro ajustado por CER (TZXA7)",t:"bono",m:"byma"},
  {s:"TZXD6",n:"Boncer · bono del Tesoro ajustado por CER (TZXD6) · vence 15/12/2026",t:"bono",m:"byma"},
  {s:"TZXD7",n:"Boncer · bono del Tesoro ajustado por CER (TZXD7)",t:"bono",m:"byma"},
  {s:"TZXD8",n:"Boncer · bono del Tesoro ajustado por CER (TZXD8)",t:"bono",m:"byma"},
  {s:"TZXM7",n:"Boncer · bono del Tesoro ajustado por CER (TZXM7) · vence 31/03/2027",t:"bono",m:"byma"},
  {s:"TZXM8",n:"Boncer · bono del Tesoro ajustado por CER (TZXM8)",t:"bono",m:"byma"},
  {s:"TZXM9",n:"Boncer · bono del Tesoro ajustado por CER (TZXM9)",t:"bono",m:"byma"},
  {s:"TZXO6",n:"Boncer · bono del Tesoro ajustado por CER (TZXO6)",t:"bono",m:"byma"},
  {s:"TZXO7",n:"Boncer · bono del Tesoro ajustado por CER (TZXO7)",t:"bono",m:"byma"},
  {s:"TZXS7",n:"Boncer · bono del Tesoro ajustado por CER (TZXS7)",t:"bono",m:"byma"},
  {s:"TZXS8",n:"Boncer · bono del Tesoro ajustado por CER (TZXS8)",t:"bono",m:"byma"},
  {s:"TZXY7",n:"Boncer · bono del Tesoro ajustado por CER (TZXY7)",t:"bono",m:"byma"},
  {s:"X29E7",n:"Lecer · letra del Tesoro ajustada por CER (X29E7)",t:"letra",m:"byma"},
  {s:"X30N6",n:"Lecer · letra del Tesoro ajustada por CER (X30N6)",t:"letra",m:"byma"},
  {s:"X30S6",n:"Lecer · letra del Tesoro ajustada por CER (X30S6)",t:"letra",m:"byma"},
  {s:"XN6D",n:"Renta fija BYMA · panel de bonos (XN6D)",t:"bono",m:"byma"},
  {s:"XS6D",n:"Renta fija BYMA · panel de bonos (XS6D)",t:"bono",m:"byma"},
  {s:"MMM",n:"3M",t:"accion_us",m:"ext"},
  {s:"AOS",n:"A. O. Smith",t:"accion_us",m:"ext"},
  {s:"ABT",n:"Abbott Laboratories",t:"accion_us",m:"ext"},
  {s:"ABBV",n:"AbbVie",t:"accion_us",m:"ext"},
  {s:"ACN",n:"Accenture",t:"accion_us",m:"ext"},
  {s:"ADBE",n:"Adobe Inc.",t:"accion_us",m:"ext"},
  {s:"AMD",n:"Advanced Micro Devices",t:"accion_us",m:"ext"},
  {s:"AES",n:"AES Corporation",t:"accion_us",m:"ext"},
  {s:"AFL",n:"Aflac",t:"accion_us",m:"ext"},
  {s:"A",n:"Agilent Technologies",t:"accion_us",m:"ext"},
  {s:"APD",n:"Air Products",t:"accion_us",m:"ext"},
  {s:"ABNB",n:"Airbnb",t:"accion_us",m:"ext"},
  {s:"AKAM",n:"Akamai Technologies",t:"accion_us",m:"ext"},
  {s:"ALB",n:"Albemarle Corporation",t:"accion_us",m:"ext"},
  {s:"ARE",n:"Alexandria Real Estate Equities",t:"accion_us",m:"ext"},
  {s:"ALGN",n:"Align Technology",t:"accion_us",m:"ext"},
  {s:"ALLE",n:"Allegion",t:"accion_us",m:"ext"},
  {s:"LNT",n:"Alliant Energy",t:"accion_us",m:"ext"},
  {s:"ALL",n:"Allstate",t:"accion_us",m:"ext"},
  {s:"GOOGL",n:"Alphabet Inc. (Class A)",t:"accion_us",m:"ext"},
  {s:"GOOG",n:"Alphabet Inc. (Class C)",t:"accion_us",m:"ext"},
  {s:"MO",n:"Altria",t:"accion_us",m:"ext"},
  {s:"AMZN",n:"Amazon",t:"accion_us",m:"ext"},
  {s:"AMCR",n:"Amcor",t:"accion_us",m:"ext"},
  {s:"AEE",n:"Ameren",t:"accion_us",m:"ext"},
  {s:"AEP",n:"American Electric Power",t:"accion_us",m:"ext"},
  {s:"AXP",n:"American Express",t:"accion_us",m:"ext"},
  {s:"AIG",n:"American International Group",t:"accion_us",m:"ext"},
  {s:"AMT",n:"American Tower",t:"accion_us",m:"ext"},
  {s:"AWK",n:"American Water Works",t:"accion_us",m:"ext"},
  {s:"AMP",n:"Ameriprise Financial",t:"accion_us",m:"ext"},
  {s:"AME",n:"Ametek",t:"accion_us",m:"ext"},
  {s:"AMGN",n:"Amgen",t:"accion_us",m:"ext"},
  {s:"APH",n:"Amphenol",t:"accion_us",m:"ext"},
  {s:"ADI",n:"Analog Devices",t:"accion_us",m:"ext"},
  {s:"AON",n:"Aon plc",t:"accion_us",m:"ext"},
  {s:"APA",n:"APA Corporation",t:"accion_us",m:"ext"},
  {s:"APO",n:"Apollo Global Management",t:"accion_us",m:"ext"},
  {s:"AAPL",n:"Apple Inc.",t:"accion_us",m:"ext"},
  {s:"AMAT",n:"Applied Materials",t:"accion_us",m:"ext"},
  {s:"APP",n:"AppLovin",t:"accion_us",m:"ext"},
  {s:"APTV",n:"Aptiv",t:"accion_us",m:"ext"},
  {s:"ACGL",n:"Arch Capital Group",t:"accion_us",m:"ext"},
  {s:"ADM",n:"Archer Daniels Midland",t:"accion_us",m:"ext"},
  {s:"ARES",n:"Ares Management",t:"accion_us",m:"ext"},
  {s:"ANET",n:"Arista Networks",t:"accion_us",m:"ext"},
  {s:"AJG",n:"Arthur J. Gallagher & Co.",t:"accion_us",m:"ext"},
  {s:"AIZ",n:"Assurant",t:"accion_us",m:"ext"},
  {s:"T",n:"AT&T",t:"accion_us",m:"ext"},
  {s:"ATO",n:"Atmos Energy",t:"accion_us",m:"ext"},
  {s:"ADSK",n:"Autodesk",t:"accion_us",m:"ext"},
  {s:"ADP",n:"Automatic Data Processing",t:"accion_us",m:"ext"},
  {s:"AZO",n:"AutoZone",t:"accion_us",m:"ext"},
  {s:"AVY",n:"Avery Dennison",t:"accion_us",m:"ext"},
  {s:"AXON",n:"Axon Enterprise",t:"accion_us",m:"ext"},
  {s:"BKR",n:"Baker Hughes",t:"accion_us",m:"ext"},
  {s:"BALL",n:"Ball Corporation",t:"accion_us",m:"ext"},
  {s:"BAC",n:"Bank of America",t:"accion_us",m:"ext"},
  {s:"BAX",n:"Baxter International",t:"accion_us",m:"ext"},
  {s:"BDX",n:"Becton Dickinson",t:"accion_us",m:"ext"},
  {s:"BRK.B",n:"Berkshire Hathaway",t:"accion_us",m:"ext"},
  {s:"BBY",n:"Best Buy",t:"accion_us",m:"ext"},
  {s:"TECH",n:"Bio-Techne",t:"accion_us",m:"ext"},
  {s:"BIIB",n:"Biogen",t:"accion_us",m:"ext"},
  {s:"BLK",n:"BlackRock",t:"accion_us",m:"ext"},
  {s:"BX",n:"Blackstone Inc.",t:"accion_us",m:"ext"},
  {s:"XYZ",n:"Block, Inc.",t:"accion_us",m:"ext"},
  {s:"BE",n:"Bloom Energy",t:"accion_us",m:"ext"},
  {s:"BNY",n:"BNY Mellon",t:"accion_us",m:"ext"},
  {s:"BA",n:"Boeing",t:"accion_us",m:"ext"},
  {s:"BKNG",n:"Booking Holdings",t:"accion_us",m:"ext"},
  {s:"BSX",n:"Boston Scientific",t:"accion_us",m:"ext"},
  {s:"BMY",n:"Bristol Myers Squibb",t:"accion_us",m:"ext"},
  {s:"AVGO",n:"Broadcom",t:"accion_us",m:"ext"},
  {s:"BR",n:"Broadridge Financial Solutions",t:"accion_us",m:"ext"},
  {s:"BRO",n:"Brown & Brown",t:"accion_us",m:"ext"},
  {s:"BF.B",n:"Brown–Forman",t:"accion_us",m:"ext"},
  {s:"BG",n:"Bunge Global",t:"accion_us",m:"ext"},
  {s:"BXP",n:"BXP, Inc.",t:"accion_us",m:"ext"},
  {s:"CHRW",n:"C.H. Robinson",t:"accion_us",m:"ext"},
  {s:"CDNS",n:"Cadence Design Systems",t:"accion_us",m:"ext"},
  {s:"CPT",n:"Camden Property Trust",t:"accion_us",m:"ext"},
  {s:"COF",n:"Capital One",t:"accion_us",m:"ext"},
  {s:"CAH",n:"Cardinal Health",t:"accion_us",m:"ext"},
  {s:"CCL",n:"Carnival Corporation",t:"accion_us",m:"ext"},
  {s:"CARR",n:"Carrier Global",t:"accion_us",m:"ext"},
  {s:"CVNA",n:"Carvana",t:"accion_us",m:"ext"},
  {s:"CASY",n:"Casey's",t:"accion_us",m:"ext"},
  {s:"CAT",n:"Caterpillar Inc.",t:"accion_us",m:"ext"},
  {s:"CBOE",n:"Cboe Global Markets",t:"accion_us",m:"ext"},
  {s:"CBRE",n:"CBRE Group",t:"accion_us",m:"ext"},
  {s:"CDW",n:"CDW Corporation",t:"accion_us",m:"ext"},
  {s:"COR",n:"Cencora",t:"accion_us",m:"ext"},
  {s:"CNC",n:"Centene Corporation",t:"accion_us",m:"ext"},
  {s:"CNP",n:"CenterPoint Energy",t:"accion_us",m:"ext"},
  {s:"CF",n:"CF Industries",t:"accion_us",m:"ext"},
  {s:"CRL",n:"Charles River Laboratories",t:"accion_us",m:"ext"},
  {s:"SCHW",n:"Charles Schwab Corporation",t:"accion_us",m:"ext"},
  {s:"CHTR",n:"Charter Communications",t:"accion_us",m:"ext"},
  {s:"CVX",n:"Chevron Corporation",t:"accion_us",m:"ext"},
  {s:"CMG",n:"Chipotle Mexican Grill",t:"accion_us",m:"ext"},
  {s:"CB",n:"Chubb Limited",t:"accion_us",m:"ext"},
  {s:"CHD",n:"Church & Dwight",t:"accion_us",m:"ext"},
  {s:"CIEN",n:"Ciena",t:"accion_us",m:"ext"},
  {s:"CI",n:"Cigna",t:"accion_us",m:"ext"},
  {s:"CINF",n:"Cincinnati Financial",t:"accion_us",m:"ext"},
  {s:"CTAS",n:"Cintas",t:"accion_us",m:"ext"},
  {s:"CSCO",n:"Cisco",t:"accion_us",m:"ext"},
  {s:"C",n:"Citigroup",t:"accion_us",m:"ext"},
  {s:"CFG",n:"Citizens Financial Group",t:"accion_us",m:"ext"},
  {s:"CLX",n:"Clorox",t:"accion_us",m:"ext"},
  {s:"CME",n:"CME Group",t:"accion_us",m:"ext"},
  {s:"CMS",n:"CMS Energy",t:"accion_us",m:"ext"},
  {s:"KO",n:"Coca-Cola Company (The)",t:"accion_us",m:"ext"},
  {s:"CTSH",n:"Cognizant",t:"accion_us",m:"ext"},
  {s:"COHR",n:"Coherent Corp.",t:"accion_us",m:"ext"},
  {s:"COIN",n:"Coinbase",t:"accion_us",m:"ext"},
  {s:"CL",n:"Colgate-Palmolive",t:"accion_us",m:"ext"},
  {s:"CMCSA",n:"Comcast",t:"accion_us",m:"ext"},
  {s:"FIX",n:"Comfort Systems USA",t:"accion_us",m:"ext"},
  {s:"COP",n:"ConocoPhillips",t:"accion_us",m:"ext"},
  {s:"ED",n:"Consolidated Edison",t:"accion_us",m:"ext"},
  {s:"STZ",n:"Constellation Brands",t:"accion_us",m:"ext"},
  {s:"CEG",n:"Constellation Energy",t:"accion_us",m:"ext"},
  {s:"COO",n:"Cooper Companies (The)",t:"accion_us",m:"ext"},
  {s:"CPRT",n:"Copart",t:"accion_us",m:"ext"},
  {s:"GLW",n:"Corning Inc.",t:"accion_us",m:"ext"},
  {s:"CPAY",n:"Corpay",t:"accion_us",m:"ext"},
  {s:"CTVA",n:"Corteva",t:"accion_us",m:"ext"},
  {s:"CSGP",n:"CoStar Group",t:"accion_us",m:"ext"},
  {s:"COST",n:"Costco",t:"accion_us",m:"ext"},
  {s:"CRH",n:"CRH plc",t:"accion_us",m:"ext"},
  {s:"CRWD",n:"CrowdStrike",t:"accion_us",m:"ext"},
  {s:"CCI",n:"Crown Castle",t:"accion_us",m:"ext"},
  {s:"CSX",n:"CSX Corporation",t:"accion_us",m:"ext"},
  {s:"CMI",n:"Cummins",t:"accion_us",m:"ext"},
  {s:"CVS",n:"CVS Health",t:"accion_us",m:"ext"},
  {s:"DHR",n:"Danaher Corporation",t:"accion_us",m:"ext"},
  {s:"DRI",n:"Darden Restaurants",t:"accion_us",m:"ext"},
  {s:"DDOG",n:"Datadog",t:"accion_us",m:"ext"},
  {s:"DVA",n:"DaVita",t:"accion_us",m:"ext"},
  {s:"DECK",n:"Deckers Brands",t:"accion_us",m:"ext"},
  {s:"DE",n:"Deere & Company",t:"accion_us",m:"ext"},
  {s:"DELL",n:"Dell Technologies",t:"accion_us",m:"ext"},
  {s:"DAL",n:"Delta Air Lines",t:"accion_us",m:"ext"},
  {s:"DVN",n:"Devon Energy",t:"accion_us",m:"ext"},
  {s:"DXCM",n:"Dexcom",t:"accion_us",m:"ext"},
  {s:"FANG",n:"Diamondback Energy",t:"accion_us",m:"ext"},
  {s:"DLR",n:"Digital Realty",t:"accion_us",m:"ext"},
  {s:"DG",n:"Dollar General",t:"accion_us",m:"ext"},
  {s:"DLTR",n:"Dollar Tree",t:"accion_us",m:"ext"},
  {s:"D",n:"Dominion Energy",t:"accion_us",m:"ext"},
  {s:"DPZ",n:"Domino's",t:"accion_us",m:"ext"},
  {s:"DASH",n:"DoorDash",t:"accion_us",m:"ext"},
  {s:"DOV",n:"Dover Corporation",t:"accion_us",m:"ext"},
  {s:"DOW",n:"Dow Inc.",t:"accion_us",m:"ext"},
  {s:"DHI",n:"D. R. Horton",t:"accion_us",m:"ext"},
  {s:"DTE",n:"DTE Energy",t:"accion_us",m:"ext"},
  {s:"DUK",n:"Duke Energy",t:"accion_us",m:"ext"},
  {s:"DD",n:"DuPont",t:"accion_us",m:"ext"},
  {s:"ETN",n:"Eaton Corporation",t:"accion_us",m:"ext"},
  {s:"EBAY",n:"eBay Inc.",t:"accion_us",m:"ext"},
  {s:"ECHO",n:"EchoStar",t:"accion_us",m:"ext"},
  {s:"ECL",n:"Ecolab",t:"accion_us",m:"ext"},
  {s:"EIX",n:"Edison International",t:"accion_us",m:"ext"},
  {s:"EW",n:"Edwards Lifesciences",t:"accion_us",m:"ext"},
  {s:"ELV",n:"Elevance Health",t:"accion_us",m:"ext"},
  {s:"EME",n:"Emcor",t:"accion_us",m:"ext"},
  {s:"EMR",n:"Emerson Electric",t:"accion_us",m:"ext"},
  {s:"ETR",n:"Entergy",t:"accion_us",m:"ext"},
  {s:"EOG",n:"EOG Resources",t:"accion_us",m:"ext"},
  {s:"EQT",n:"EQT Corporation",t:"accion_us",m:"ext"},
  {s:"EFX",n:"Equifax",t:"accion_us",m:"ext"},
  {s:"EQIX",n:"Equinix",t:"accion_us",m:"ext"},
  {s:"ERIE",n:"Erie Indemnity",t:"accion_us",m:"ext"},
  {s:"ESS",n:"Essex Property Trust",t:"accion_us",m:"ext"},
  {s:"EL",n:"Estée Lauder Companies (The)",t:"accion_us",m:"ext"},
  {s:"EG",n:"Everest Group",t:"accion_us",m:"ext"},
  {s:"EVRG",n:"Evergy",t:"accion_us",m:"ext"},
  {s:"P",n:"Everpure",t:"accion_us",m:"ext"},
  {s:"ES",n:"Eversource Energy",t:"accion_us",m:"ext"},
  {s:"EXC",n:"Exelon",t:"accion_us",m:"ext"},
  {s:"EXE",n:"Expand Energy",t:"accion_us",m:"ext"},
  {s:"EXPE",n:"Expedia Group",t:"accion_us",m:"ext"},
  {s:"EXPD",n:"Expeditors International",t:"accion_us",m:"ext"},
  {s:"EXR",n:"Extra Space Storage",t:"accion_us",m:"ext"},
  {s:"XOM",n:"ExxonMobil",t:"accion_us",m:"ext"},
  {s:"FFIV",n:"F5, Inc.",t:"accion_us",m:"ext"},
  {s:"FDS",n:"FactSet",t:"accion_us",m:"ext"},
  {s:"FICO",n:"Fair Isaac",t:"accion_us",m:"ext"},
  {s:"FAST",n:"Fastenal",t:"accion_us",m:"ext"},
  {s:"FRT",n:"Federal Realty Investment Trust",t:"accion_us",m:"ext"},
  {s:"FDX",n:"FedEx",t:"accion_us",m:"ext"},
  {s:"FDXF",n:"FedEx Freight",t:"accion_us",m:"ext"},
  {s:"FERG",n:"Ferguson Enterprises",t:"accion_us",m:"ext"},
  {s:"FIS",n:"Fidelity National Information Services",t:"accion_us",m:"ext"},
  {s:"FITB",n:"Fifth Third Bancorp",t:"accion_us",m:"ext"},
  {s:"FSLR",n:"First Solar",t:"accion_us",m:"ext"},
  {s:"FE",n:"FirstEnergy",t:"accion_us",m:"ext"},
  {s:"FISV",n:"Fiserv",t:"accion_us",m:"ext"},
  {s:"FLEX",n:"Flex Ltd.",t:"accion_us",m:"ext"},
  {s:"F",n:"Ford Motor Company",t:"accion_us",m:"ext"},
  {s:"FTNT",n:"Fortinet",t:"accion_us",m:"ext"},
  {s:"FTV",n:"Fortive",t:"accion_us",m:"ext"},
  {s:"FOXA",n:"Fox Corporation (Class A)",t:"accion_us",m:"ext"},
  {s:"FOX",n:"Fox Corporation (Class B)",t:"accion_us",m:"ext"},
  {s:"BEN",n:"Franklin Resources",t:"accion_us",m:"ext"},
  {s:"FCX",n:"Freeport-McMoRan",t:"accion_us",m:"ext"},
  {s:"GRMN",n:"Garmin",t:"accion_us",m:"ext"},
  {s:"IT",n:"Gartner",t:"accion_us",m:"ext"},
  {s:"GE",n:"GE Aerospace",t:"accion_us",m:"ext"},
  {s:"GEHC",n:"GE HealthCare",t:"accion_us",m:"ext"},
  {s:"GEV",n:"GE Vernova",t:"accion_us",m:"ext"},
  {s:"GEN",n:"Gen Digital",t:"accion_us",m:"ext"},
  {s:"GNRC",n:"Generac",t:"accion_us",m:"ext"},
  {s:"GD",n:"General Dynamics",t:"accion_us",m:"ext"},
  {s:"GIS",n:"General Mills",t:"accion_us",m:"ext"},
  {s:"GM",n:"General Motors",t:"accion_us",m:"ext"},
  {s:"GPC",n:"Genuine Parts Company",t:"accion_us",m:"ext"},
  {s:"GILD",n:"Gilead Sciences",t:"accion_us",m:"ext"},
  {s:"GPN",n:"Global Payments",t:"accion_us",m:"ext"},
  {s:"GL",n:"Globe Life",t:"accion_us",m:"ext"},
  {s:"GDDY",n:"GoDaddy",t:"accion_us",m:"ext"},
  {s:"GS",n:"Goldman Sachs",t:"accion_us",m:"ext"},
  {s:"HAL",n:"Halliburton",t:"accion_us",m:"ext"},
  {s:"HIG",n:"Hartford (The)",t:"accion_us",m:"ext"},
  {s:"HAS",n:"Hasbro",t:"accion_us",m:"ext"},
  {s:"HCA",n:"HCA Healthcare",t:"accion_us",m:"ext"},
  {s:"DOC",n:"Healthpeak Properties",t:"accion_us",m:"ext"},
  {s:"HSIC",n:"Henry Schein",t:"accion_us",m:"ext"},
  {s:"HSY",n:"Hershey Company (The)",t:"accion_us",m:"ext"},
  {s:"HPE",n:"Hewlett Packard Enterprise",t:"accion_us",m:"ext"},
  {s:"HLT",n:"Hilton Worldwide",t:"accion_us",m:"ext"},
  {s:"HD",n:"Home Depot (The)",t:"accion_us",m:"ext"},
  {s:"HONA",n:"Honeywell Aerospace",t:"accion_us",m:"ext"},
  {s:"HON",n:"Honeywell Technologies",t:"accion_us",m:"ext"},
  {s:"HRL",n:"Hormel Foods",t:"accion_us",m:"ext"},
  {s:"HST",n:"Host Hotels & Resorts",t:"accion_us",m:"ext"},
  {s:"HWM",n:"Howmet Aerospace",t:"accion_us",m:"ext"},
  {s:"HPQ",n:"HP Inc.",t:"accion_us",m:"ext"},
  {s:"HUBB",n:"Hubbell Incorporated",t:"accion_us",m:"ext"},
  {s:"HUM",n:"Humana",t:"accion_us",m:"ext"},
  {s:"HBAN",n:"Huntington Bancshares",t:"accion_us",m:"ext"},
  {s:"HII",n:"Huntington Ingalls Industries",t:"accion_us",m:"ext"},
  {s:"IBM",n:"IBM",t:"accion_us",m:"ext"},
  {s:"IEX",n:"IDEX Corporation",t:"accion_us",m:"ext"},
  {s:"IDXX",n:"Idexx Laboratories",t:"accion_us",m:"ext"},
  {s:"ITW",n:"Illinois Tool Works",t:"accion_us",m:"ext"},
  {s:"ILMN",n:"Illumina, Inc.",t:"accion_us",m:"ext"},
  {s:"INCY",n:"Incyte",t:"accion_us",m:"ext"},
  {s:"IR",n:"Ingersoll Rand",t:"accion_us",m:"ext"},
  {s:"PODD",n:"Insulet Corporation",t:"accion_us",m:"ext"},
  {s:"INTC",n:"Intel",t:"accion_us",m:"ext"},
  {s:"IBKR",n:"Interactive Brokers",t:"accion_us",m:"ext"},
  {s:"ICE",n:"Intercontinental Exchange",t:"accion_us",m:"ext"},
  {s:"IFF",n:"International Flavors & Fragrances",t:"accion_us",m:"ext"},
  {s:"IP",n:"International Paper",t:"accion_us",m:"ext"},
  {s:"INTU",n:"Intuit",t:"accion_us",m:"ext"},
  {s:"ISRG",n:"Intuitive Surgical",t:"accion_us",m:"ext"},
  {s:"IVZ",n:"Invesco",t:"accion_us",m:"ext"},
  {s:"INVH",n:"Invitation Homes",t:"accion_us",m:"ext"},
  {s:"IQV",n:"IQVIA",t:"accion_us",m:"ext"},
  {s:"IRM",n:"Iron Mountain",t:"accion_us",m:"ext"},
  {s:"JBHT",n:"J.B. Hunt",t:"accion_us",m:"ext"},
  {s:"JBL",n:"Jabil",t:"accion_us",m:"ext"},
  {s:"JKHY",n:"Jack Henry & Associates",t:"accion_us",m:"ext"},
  {s:"J",n:"Jacobs Solutions",t:"accion_us",m:"ext"},
  {s:"JNJ",n:"Johnson & Johnson",t:"accion_us",m:"ext"},
  {s:"JCI",n:"Johnson Controls",t:"accion_us",m:"ext"},
  {s:"JPM",n:"JPMorgan Chase",t:"accion_us",m:"ext"},
  {s:"KVUE",n:"Kenvue",t:"accion_us",m:"ext"},
  {s:"KDP",n:"Keurig Dr Pepper",t:"accion_us",m:"ext"},
  {s:"KEY",n:"KeyCorp",t:"accion_us",m:"ext"},
  {s:"KEYS",n:"Keysight Technologies",t:"accion_us",m:"ext"},
  {s:"KMB",n:"Kimberly-Clark",t:"accion_us",m:"ext"},
  {s:"KIM",n:"Kimco Realty",t:"accion_us",m:"ext"},
  {s:"KMI",n:"Kinder Morgan",t:"accion_us",m:"ext"},
  {s:"KKR",n:"KKR & Co.",t:"accion_us",m:"ext"},
  {s:"KLAC",n:"KLA Corporation",t:"accion_us",m:"ext"},
  {s:"KHC",n:"Kraft Heinz",t:"accion_us",m:"ext"},
  {s:"KR",n:"Kroger",t:"accion_us",m:"ext"},
  {s:"LHX",n:"L3Harris",t:"accion_us",m:"ext"},
  {s:"LH",n:"Labcorp",t:"accion_us",m:"ext"},
  {s:"LRCX",n:"Lam Research",t:"accion_us",m:"ext"},
  {s:"LVS",n:"Las Vegas Sands",t:"accion_us",m:"ext"},
  {s:"LDOS",n:"Leidos",t:"accion_us",m:"ext"},
  {s:"LEN",n:"Lennar",t:"accion_us",m:"ext"},
  {s:"LII",n:"Lennox International",t:"accion_us",m:"ext"},
  {s:"LLY",n:"Lilly (Eli)",t:"accion_us",m:"ext"},
  {s:"LIN",n:"Linde plc",t:"accion_us",m:"ext"},
  {s:"LYV",n:"Live Nation Entertainment",t:"accion_us",m:"ext"},
  {s:"LMT",n:"Lockheed Martin",t:"accion_us",m:"ext"},
  {s:"L",n:"Loews Corporation",t:"accion_us",m:"ext"},
  {s:"LOW",n:"Lowe's",t:"accion_us",m:"ext"},
  {s:"LULU",n:"Lululemon Athletica",t:"accion_us",m:"ext"},
  {s:"LITE",n:"Lumentum",t:"accion_us",m:"ext"},
  {s:"LYB",n:"LyondellBasell",t:"accion_us",m:"ext"},
  {s:"MTB",n:"M&T Bank",t:"accion_us",m:"ext"},
  {s:"MPC",n:"Marathon Petroleum",t:"accion_us",m:"ext"},
  {s:"MAR",n:"Marriott International",t:"accion_us",m:"ext"},
  {s:"MRSH",n:"Marsh McLennan",t:"accion_us",m:"ext"},
  {s:"MLM",n:"Martin Marietta Materials",t:"accion_us",m:"ext"},
  {s:"MRVL",n:"Marvell Technology",t:"accion_us",m:"ext"},
  {s:"MAS",n:"Masco",t:"accion_us",m:"ext"},
  {s:"MA",n:"Mastercard",t:"accion_us",m:"ext"},
  {s:"MKC",n:"McCormick & Company",t:"accion_us",m:"ext"},
  {s:"MCD",n:"McDonald's",t:"accion_us",m:"ext"},
  {s:"MCK",n:"McKesson Corporation",t:"accion_us",m:"ext"},
  {s:"MDT",n:"Medtronic",t:"accion_us",m:"ext"},
  {s:"MRK",n:"Merck & Co.",t:"accion_us",m:"ext"},
  {s:"META",n:"Meta Platforms",t:"accion_us",m:"ext"},
  {s:"MET",n:"MetLife",t:"accion_us",m:"ext"},
  {s:"MTD",n:"Mettler Toledo",t:"accion_us",m:"ext"},
  {s:"MGM",n:"MGM Resorts",t:"accion_us",m:"ext"},
  {s:"MCHP",n:"Microchip Technology",t:"accion_us",m:"ext"},
  {s:"MU",n:"Micron Technology",t:"accion_us",m:"ext"},
  {s:"MSFT",n:"Microsoft",t:"accion_us",m:"ext"},
  {s:"MAA",n:"Mid-America Apartment Communities",t:"accion_us",m:"ext"},
  {s:"MRNA",n:"Moderna",t:"accion_us",m:"ext"},
  {s:"MDLZ",n:"Mondelez International",t:"accion_us",m:"ext"},
  {s:"MPWR",n:"Monolithic Power Systems",t:"accion_us",m:"ext"},
  {s:"MNST",n:"Monster Beverage",t:"accion_us",m:"ext"},
  {s:"MCO",n:"Moody's Corporation",t:"accion_us",m:"ext"},
  {s:"MS",n:"Morgan Stanley",t:"accion_us",m:"ext"},
  {s:"MOS",n:"Mosaic Company (The)",t:"accion_us",m:"ext"},
  {s:"MSI",n:"Motorola Solutions",t:"accion_us",m:"ext"},
  {s:"MSCI",n:"MSCI",t:"accion_us",m:"ext"},
  {s:"NDAQ",n:"Nasdaq, Inc.",t:"accion_us",m:"ext"},
  {s:"NTAP",n:"NetApp",t:"accion_us",m:"ext"},
  {s:"NFLX",n:"Netflix",t:"accion_us",m:"ext"},
  {s:"NEM",n:"Newmont",t:"accion_us",m:"ext"},
  {s:"NWSA",n:"News Corp (Class A)",t:"accion_us",m:"ext"},
  {s:"NWS",n:"News Corp (Class B)",t:"accion_us",m:"ext"},
  {s:"NEE",n:"NextEra Energy",t:"accion_us",m:"ext"},
  {s:"NKE",n:"Nike, Inc.",t:"accion_us",m:"ext"},
  {s:"NI",n:"NiSource",t:"accion_us",m:"ext"},
  {s:"NDSN",n:"Nordson Corporation",t:"accion_us",m:"ext"},
  {s:"NSC",n:"Norfolk Southern",t:"accion_us",m:"ext"},
  {s:"NTRS",n:"Northern Trust",t:"accion_us",m:"ext"},
  {s:"NOC",n:"Northrop Grumman",t:"accion_us",m:"ext"},
  {s:"NCLH",n:"Norwegian Cruise Line Holdings",t:"accion_us",m:"ext"},
  {s:"NRG",n:"NRG Energy",t:"accion_us",m:"ext"},
  {s:"NUE",n:"Nucor",t:"accion_us",m:"ext"},
  {s:"NVDA",n:"Nvidia",t:"accion_us",m:"ext"},
  {s:"NVR",n:"NVR, Inc.",t:"accion_us",m:"ext"},
  {s:"NXPI",n:"NXP Semiconductors",t:"accion_us",m:"ext"},
  {s:"ORLY",n:"O'Reilly Automotive",t:"accion_us",m:"ext"},
  {s:"OXY",n:"Occidental Petroleum",t:"accion_us",m:"ext"},
  {s:"ODFL",n:"Old Dominion",t:"accion_us",m:"ext"},
  {s:"OMC",n:"Omnicom Group",t:"accion_us",m:"ext"},
  {s:"ON",n:"ON Semiconductor",t:"accion_us",m:"ext"},
  {s:"OKE",n:"Oneok",t:"accion_us",m:"ext"},
  {s:"ORCL",n:"Oracle Corporation",t:"accion_us",m:"ext"},
  {s:"OTIS",n:"Otis Worldwide",t:"accion_us",m:"ext"},
  {s:"PCAR",n:"Paccar",t:"accion_us",m:"ext"},
  {s:"PKG",n:"Packaging Corporation of America",t:"accion_us",m:"ext"},
  {s:"PLTR",n:"Palantir Technologies",t:"accion_us",m:"ext"},
  {s:"PANW",n:"Palo Alto Networks",t:"accion_us",m:"ext"},
  {s:"PSKY",n:"Paramount Skydance Corporation",t:"accion_us",m:"ext"},
  {s:"PH",n:"Parker Hannifin",t:"accion_us",m:"ext"},
  {s:"PAYX",n:"Paychex",t:"accion_us",m:"ext"},
  {s:"PYPL",n:"PayPal",t:"accion_us",m:"ext"},
  {s:"PNR",n:"Pentair",t:"accion_us",m:"ext"},
  {s:"PEP",n:"PepsiCo",t:"accion_us",m:"ext"},
  {s:"PFE",n:"Pfizer",t:"accion_us",m:"ext"},
  {s:"PCG",n:"PG&E Corporation",t:"accion_us",m:"ext"},
  {s:"PM",n:"Philip Morris International",t:"accion_us",m:"ext"},
  {s:"PSX",n:"Phillips 66",t:"accion_us",m:"ext"},
  {s:"PNW",n:"Pinnacle West Capital",t:"accion_us",m:"ext"},
  {s:"PNC",n:"PNC Financial Services",t:"accion_us",m:"ext"},
  {s:"PPG",n:"PPG Industries",t:"accion_us",m:"ext"},
  {s:"PPL",n:"PPL Corporation",t:"accion_us",m:"ext"},
  {s:"PFG",n:"Principal Financial Group",t:"accion_us",m:"ext"},
  {s:"PG",n:"Procter & Gamble",t:"accion_us",m:"ext"},
  {s:"PGR",n:"Progressive Corporation",t:"accion_us",m:"ext"},
  {s:"PLD",n:"Prologis",t:"accion_us",m:"ext"},
  {s:"PRU",n:"Prudential Financial",t:"accion_us",m:"ext"},
  {s:"PEG",n:"Public Service Enterprise Group",t:"accion_us",m:"ext"},
  {s:"PTC",n:"PTC Inc.",t:"accion_us",m:"ext"},
  {s:"PSA",n:"Public Storage",t:"accion_us",m:"ext"},
  {s:"PHM",n:"PulteGroup",t:"accion_us",m:"ext"},
  {s:"PWR",n:"Quanta Services",t:"accion_us",m:"ext"},
  {s:"QCOM",n:"Qualcomm",t:"accion_us",m:"ext"},
  {s:"DGX",n:"Quest Diagnostics",t:"accion_us",m:"ext"},
  {s:"Q",n:"Qnity Electronics",t:"accion_us",m:"ext"},
  {s:"RL",n:"Ralph Lauren Corporation",t:"accion_us",m:"ext"},
  {s:"RJF",n:"Raymond James Financial",t:"accion_us",m:"ext"},
  {s:"RDDT",n:"Reddit",t:"accion_us",m:"ext"},
  {s:"RTX",n:"RTX Corporation",t:"accion_us",m:"ext"},
  {s:"O",n:"Realty Income",t:"accion_us",m:"ext"},
  {s:"REG",n:"Regency Centers",t:"accion_us",m:"ext"},
  {s:"REGN",n:"Regeneron Pharmaceuticals",t:"accion_us",m:"ext"},
  {s:"RF",n:"Regions Financial Corporation",t:"accion_us",m:"ext"},
  {s:"RSG",n:"Republic Services",t:"accion_us",m:"ext"},
  {s:"RMD",n:"ResMed |",t:"accion_us",m:"ext"},
  {s:"RVTY",n:"Revvity",t:"accion_us",m:"ext"},
  {s:"HOOD",n:"Robinhood Markets",t:"accion_us",m:"ext"},
  {s:"ROK",n:"Rockwell Automation",t:"accion_us",m:"ext"},
  {s:"ROL",n:"Rollins, Inc.",t:"accion_us",m:"ext"},
  {s:"ROP",n:"Roper Technologies",t:"accion_us",m:"ext"},
  {s:"ROST",n:"Ross Stores",t:"accion_us",m:"ext"},
  {s:"RCL",n:"Royal Caribbean Group",t:"accion_us",m:"ext"},
  {s:"SPGI",n:"S&P Global",t:"accion_us",m:"ext"},
  {s:"CRM",n:"Salesforce",t:"accion_us",m:"ext"},
  {s:"SNDK",n:"Sandisk",t:"accion_us",m:"ext"},
  {s:"SBAC",n:"SBA Communications",t:"accion_us",m:"ext"},
  {s:"SLB",n:"Schlumberger",t:"accion_us",m:"ext"},
  {s:"STX",n:"Seagate Technology",t:"accion_us",m:"ext"},
  {s:"SRE",n:"Sempra",t:"accion_us",m:"ext"},
  {s:"NOW",n:"ServiceNow",t:"accion_us",m:"ext"},
  {s:"SHW",n:"Sherwin-Williams",t:"accion_us",m:"ext"},
  {s:"SPG",n:"Simon Property Group",t:"accion_us",m:"ext"},
  {s:"SWKS",n:"Skyworks Solutions",t:"accion_us",m:"ext"},
  {s:"SJM",n:"J.M. Smucker Company (The)",t:"accion_us",m:"ext"},
  {s:"SW",n:"Smurfit Westrock",t:"accion_us",m:"ext"},
  {s:"SNA",n:"Snap-on",t:"accion_us",m:"ext"},
  {s:"SOLV",n:"Solventum",t:"accion_us",m:"ext"},
  {s:"SO",n:"Southern Company",t:"accion_us",m:"ext"},
  {s:"LUV",n:"Southwest Airlines",t:"accion_us",m:"ext"},
  {s:"SWK",n:"Stanley Black & Decker",t:"accion_us",m:"ext"},
  {s:"SBUX",n:"Starbucks",t:"accion_us",m:"ext"},
  {s:"STT",n:"State Street Corporation",t:"accion_us",m:"ext"},
  {s:"STLD",n:"Steel Dynamics",t:"accion_us",m:"ext"},
  {s:"STE",n:"Steris",t:"accion_us",m:"ext"},
  {s:"SYK",n:"Stryker Corporation",t:"accion_us",m:"ext"},
  {s:"SMCI",n:"Supermicro",t:"accion_us",m:"ext"},
  {s:"SYF",n:"Synchrony Financial",t:"accion_us",m:"ext"},
  {s:"SNPS",n:"Synopsys",t:"accion_us",m:"ext"},
  {s:"SYY",n:"Sysco",t:"accion_us",m:"ext"},
  {s:"TMUS",n:"T-Mobile US",t:"accion_us",m:"ext"},
  {s:"TROW",n:"T. Rowe Price",t:"accion_us",m:"ext"},
  {s:"TTWO",n:"Take-Two Interactive",t:"accion_us",m:"ext"},
  {s:"TPR",n:"Tapestry, Inc.",t:"accion_us",m:"ext"},
  {s:"TRGP",n:"Targa Resources",t:"accion_us",m:"ext"},
  {s:"TGT",n:"Target Corporation",t:"accion_us",m:"ext"},
  {s:"TEL",n:"TE Connectivity",t:"accion_us",m:"ext"},
  {s:"TDY",n:"Teledyne Technologies",t:"accion_us",m:"ext"},
  {s:"TER",n:"Teradyne",t:"accion_us",m:"ext"},
  {s:"TSLA",n:"Tesla, Inc.",t:"accion_us",m:"ext"},
  {s:"TXN",n:"Texas Instruments",t:"accion_us",m:"ext"},
  {s:"TPL",n:"Texas Pacific Land Corporation",t:"accion_us",m:"ext"},
  {s:"TXT",n:"Textron",t:"accion_us",m:"ext"},
  {s:"TMO",n:"Thermo Fisher Scientific",t:"accion_us",m:"ext"},
  {s:"TJX",n:"TJX Companies",t:"accion_us",m:"ext"},
  {s:"TKO",n:"TKO Group Holdings",t:"accion_us",m:"ext"},
  {s:"TSCO",n:"Tractor Supply",t:"accion_us",m:"ext"},
  {s:"TT",n:"Trane Technologies",t:"accion_us",m:"ext"},
  {s:"TDG",n:"TransDigm Group",t:"accion_us",m:"ext"},
  {s:"TRV",n:"Travelers Companies (The)",t:"accion_us",m:"ext"},
  {s:"TRMB",n:"Trimble Inc.",t:"accion_us",m:"ext"},
  {s:"TFC",n:"Truist Financial",t:"accion_us",m:"ext"},
  {s:"TYL",n:"Tyler Technologies",t:"accion_us",m:"ext"},
  {s:"TSN",n:"Tyson Foods",t:"accion_us",m:"ext"},
  {s:"USB",n:"U.S. Bancorp",t:"accion_us",m:"ext"},
  {s:"UBER",n:"Uber",t:"accion_us",m:"ext"},
  {s:"UDR",n:"UDR, Inc.",t:"accion_us",m:"ext"},
  {s:"ULTA",n:"Ulta Beauty",t:"accion_us",m:"ext"},
  {s:"UNP",n:"Union Pacific Corporation",t:"accion_us",m:"ext"},
  {s:"UAL",n:"United Airlines Holdings",t:"accion_us",m:"ext"},
  {s:"UPS",n:"United Parcel Service",t:"accion_us",m:"ext"},
  {s:"URI",n:"United Rentals",t:"accion_us",m:"ext"},
  {s:"UNH",n:"UnitedHealth Group",t:"accion_us",m:"ext"},
  {s:"UHS",n:"Universal Health Services",t:"accion_us",m:"ext"},
  {s:"VLO",n:"Valero Energy",t:"accion_us",m:"ext"},
  {s:"VEEV",n:"Veeva Systems",t:"accion_us",m:"ext"},
  {s:"VTR",n:"Ventas",t:"accion_us",m:"ext"},
  {s:"VLTO",n:"Veralto",t:"accion_us",m:"ext"},
  {s:"VRSN",n:"Verisign",t:"accion_us",m:"ext"},
  {s:"VRSK",n:"Verisk Analytics",t:"accion_us",m:"ext"},
  {s:"VZ",n:"Verizon",t:"accion_us",m:"ext"},
  {s:"VRTX",n:"Vertex Pharmaceuticals",t:"accion_us",m:"ext"},
  {s:"VRT",n:"Vertiv",t:"accion_us",m:"ext"},
  {s:"VTRS",n:"Viatris",t:"accion_us",m:"ext"},
  {s:"VICI",n:"Vici Properties",t:"accion_us",m:"ext"},
  {s:"V",n:"Visa Inc.",t:"accion_us",m:"ext"},
  {s:"VST",n:"Vistra Corp .",t:"accion_us",m:"ext"},
  {s:"VMRK",n:"Vivmark Residential",t:"accion_us",m:"ext"},
  {s:"VMC",n:"Vulcan Materials Company",t:"accion_us",m:"ext"},
  {s:"WRB",n:"W. R. Berkley Corporation",t:"accion_us",m:"ext"},
  {s:"GWW",n:"W. W. Grainger",t:"accion_us",m:"ext"},
  {s:"WAB",n:"Wabtec",t:"accion_us",m:"ext"},
  {s:"WMT",n:"Walmart",t:"accion_us",m:"ext"},
  {s:"DIS",n:"Walt Disney Company (The)",t:"accion_us",m:"ext"},
  {s:"WBD",n:"Warner Bros. Discovery",t:"accion_us",m:"ext"},
  {s:"WM",n:"Waste Management",t:"accion_us",m:"ext"},
  {s:"WAT",n:"Waters Corporation",t:"accion_us",m:"ext"},
  {s:"WEC",n:"WEC Energy Group",t:"accion_us",m:"ext"},
  {s:"WFC",n:"Wells Fargo",t:"accion_us",m:"ext"},
  {s:"WELL",n:"Welltower",t:"accion_us",m:"ext"},
  {s:"WST",n:"West Pharmaceutical Services",t:"accion_us",m:"ext"},
  {s:"WDC",n:"Western Digital",t:"accion_us",m:"ext"},
  {s:"WY",n:"Weyerhaeuser",t:"accion_us",m:"ext"},
  {s:"WSM",n:"Williams-Sonoma, Inc.",t:"accion_us",m:"ext"},
  {s:"WMB",n:"Williams Companies",t:"accion_us",m:"ext"},
  {s:"WTW",n:"Willis Towers Watson",t:"accion_us",m:"ext"},
  {s:"WDAY",n:"Workday, Inc.",t:"accion_us",m:"ext"},
  {s:"WYNN",n:"Wynn Resorts",t:"accion_us",m:"ext"},
  {s:"XEL",n:"Xcel Energy",t:"accion_us",m:"ext"},
  {s:"XYL",n:"Xylem Inc.",t:"accion_us",m:"ext"},
  {s:"YUM",n:"Yum! Brands",t:"accion_us",m:"ext"},
  {s:"ZBRA",n:"Zebra Technologies",t:"accion_us",m:"ext"},
  {s:"ZBH",n:"Zimmer Biomet",t:"accion_us",m:"ext"},
  {s:"ZTS",n:"Zoetis",t:"accion_us",m:"ext"},
  {s:"ALNY",n:"Alnylam Pharmaceuticals",t:"accion_us",m:"ext"},
  {s:"ARM",n:"Arm Holdings",t:"accion_us",m:"ext"},
  {s:"ASML",n:"ASML Holding",t:"accion_us",m:"ext"},
  {s:"ALAB",n:"Astera Labs",t:"accion_us",m:"ext"},
  {s:"CCEP",n:"Coca-Cola Europacific Partners",t:"accion_us",m:"ext"},
  {s:"CRWV",n:"CoreWeave",t:"accion_us",m:"ext"},
  {s:"FER",n:"Ferrovial",t:"accion_us",m:"ext"},
  {s:"MELI",n:"Mercado Libre",t:"accion_us",m:"ext"},
  {s:"MSTR",n:"MicroStrategy",t:"accion_us",m:"ext"},
  {s:"NBIS",n:"Nebius Group",t:"accion_us",m:"ext"},
  {s:"PDD",n:"PDD Holdings",t:"accion_us",m:"ext"},
  {s:"RKLB",n:"Rocket Lab",t:"accion_us",m:"ext"},
  {s:"SHOP",n:"Shopify",t:"accion_us",m:"ext"},
  {s:"SPCX",n:"SpaceX",t:"accion_us",m:"ext"},
  {s:"TRI",n:"Thomson Reuters",t:"accion_us",m:"ext"},
  {s:"SPY",n:"SPDR S&P 500 ETF Trust",t:"etf",m:"ext"},
  {s:"IVV",n:"iShares Core S&P 500 ETF",t:"etf",m:"ext"},
  {s:"VOO",n:"Vanguard S&P 500 ETF",t:"etf",m:"ext"},
  {s:"VTI",n:"Vanguard Total Stock Market ETF",t:"etf",m:"ext"},
  {s:"QQQ",n:"Invesco QQQ Trust",t:"etf",m:"ext"},
  {s:"QQQM",n:"Invesco NASDAQ 100 ETF",t:"etf",m:"ext"},
  {s:"DIA",n:"SPDR Dow Jones Industrial Average ETF Trust",t:"etf",m:"ext"},
  {s:"IWM",n:"iShares Russell 2000 ETF",t:"etf",m:"ext"},
  {s:"IWF",n:"iShares Russell 1000 Growth ETF",t:"etf",m:"ext"},
  {s:"IWD",n:"iShares Russell 1000 Value ETF",t:"etf",m:"ext"},
  {s:"VUG",n:"Vanguard Growth ETF",t:"etf",m:"ext"},
  {s:"VTV",n:"Vanguard Value ETF",t:"etf",m:"ext"},
  {s:"RSP",n:"Invesco S&P 500 Equal Weight ETF",t:"etf",m:"ext"},
  {s:"MDY",n:"SPDR S&P MidCap 400 ETF Trust",t:"etf",m:"ext"},
  {s:"IJH",n:"iShares Core S&P Mid-Cap ETF",t:"etf",m:"ext"},
  {s:"IJR",n:"iShares Core S&P Small-Cap ETF",t:"etf",m:"ext"},
  {s:"VEA",n:"Vanguard FTSE Developed Markets ETF",t:"etf",m:"ext"},
  {s:"VWO",n:"Vanguard FTSE Emerging Markets ETF",t:"etf",m:"ext"},
  {s:"EEM",n:"iShares MSCI Emerging Markets ETF",t:"etf",m:"ext"},
  {s:"IEMG",n:"iShares Core MSCI Emerging Markets ETF",t:"etf",m:"ext"},
  {s:"EFA",n:"iShares MSCI EAFE ETF",t:"etf",m:"ext"},
  {s:"IEFA",n:"iShares Core MSCI EAFE ETF",t:"etf",m:"ext"},
  {s:"VXUS",n:"Vanguard Total International Stock ETF",t:"etf",m:"ext"},
  {s:"ACWI",n:"iShares MSCI ACWI ETF",t:"etf",m:"ext"},
  {s:"VGK",n:"Vanguard FTSE Europe ETF",t:"etf",m:"ext"},
  {s:"EZU",n:"iShares MSCI Eurozone ETF",t:"etf",m:"ext"},
  {s:"EWZ",n:"iShares MSCI Brazil ETF",t:"etf",m:"ext"},
  {s:"EWJ",n:"iShares MSCI Japan ETF",t:"etf",m:"ext"},
  {s:"FXI",n:"iShares China Large-Cap ETF",t:"etf",m:"ext"},
  {s:"MCHI",n:"iShares MSCI China ETF",t:"etf",m:"ext"},
  {s:"KWEB",n:"KraneShares CSI China Internet ETF",t:"etf",m:"ext"},
  {s:"INDA",n:"iShares MSCI India ETF",t:"etf",m:"ext"},
  {s:"EWW",n:"iShares MSCI Mexico ETF",t:"etf",m:"ext"},
  {s:"EWG",n:"iShares MSCI Germany ETF",t:"etf",m:"ext"},
  {s:"EWU",n:"iShares MSCI United Kingdom ETF",t:"etf",m:"ext"},
  {s:"EWC",n:"iShares MSCI Canada ETF",t:"etf",m:"ext"},
  {s:"EWA",n:"iShares MSCI Australia ETF",t:"etf",m:"ext"},
  {s:"EWY",n:"iShares MSCI South Korea ETF",t:"etf",m:"ext"},
  {s:"EWT",n:"iShares MSCI Taiwan ETF",t:"etf",m:"ext"},
  {s:"ILF",n:"iShares Latin America 40 ETF",t:"etf",m:"ext"},
  {s:"ARGT",n:"Global X MSCI Argentina ETF",t:"etf",m:"ext"},
  {s:"XLK",n:"Technology Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLF",n:"Financial Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLE",n:"Energy Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLV",n:"Health Care Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLY",n:"Consumer Discretionary Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLP",n:"Consumer Staples Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLI",n:"Industrial Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLU",n:"Utilities Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLB",n:"Materials Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLRE",n:"Real Estate Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"XLC",n:"Communication Services Select Sector SPDR Fund",t:"etf",m:"ext"},
  {s:"SMH",n:"VanEck Semiconductor ETF",t:"etf",m:"ext"},
  {s:"SOXX",n:"iShares Semiconductor ETF",t:"etf",m:"ext"},
  {s:"XBI",n:"SPDR S&P Biotech ETF",t:"etf",m:"ext"},
  {s:"IBB",n:"iShares Biotechnology ETF",t:"etf",m:"ext"},
  {s:"KRE",n:"SPDR S&P Regional Banking ETF",t:"etf",m:"ext"},
  {s:"XOP",n:"SPDR S&P Oil & Gas Exploration & Production ETF",t:"etf",m:"ext"},
  {s:"ITA",n:"iShares U.S. Aerospace & Defense ETF",t:"etf",m:"ext"},
  {s:"VNQ",n:"Vanguard Real Estate ETF",t:"etf",m:"ext"},
  {s:"ARKK",n:"ARK Innovation ETF",t:"etf",m:"ext"},
  {s:"ARKG",n:"ARK Genomic Revolution ETF",t:"etf",m:"ext"},
  {s:"ARKW",n:"ARK Next Generation Internet ETF",t:"etf",m:"ext"},
  {s:"ARKF",n:"ARK Fintech Innovation ETF",t:"etf",m:"ext"},
  {s:"TQQQ",n:"ProShares UltraPro QQQ",t:"etf",m:"ext"},
  {s:"SQQQ",n:"ProShares UltraPro Short QQQ",t:"etf",m:"ext"},
  {s:"SOXL",n:"Direxion Daily Semiconductor Bull 3X Shares",t:"etf",m:"ext"},
  {s:"SPXL",n:"Direxion Daily S&P 500 Bull 3X Shares",t:"etf",m:"ext"},
  {s:"UVXY",n:"ProShares Ultra VIX Short-Term Futures ETF",t:"etf",m:"ext"},
  {s:"VXX",n:"iPath Series B S&P 500 VIX Short-Term Futures ETN",t:"etf",m:"ext"},
  {s:"GLD",n:"SPDR Gold Shares",t:"etf",m:"ext"},
  {s:"IAU",n:"iShares Gold Trust",t:"etf",m:"ext"},
  {s:"SLV",n:"iShares Silver Trust",t:"etf",m:"ext"},
  {s:"GDX",n:"VanEck Gold Miners ETF",t:"etf",m:"ext"},
  {s:"GDXJ",n:"VanEck Junior Gold Miners ETF",t:"etf",m:"ext"},
  {s:"USO",n:"United States Oil Fund",t:"etf",m:"ext"},
  {s:"UNG",n:"United States Natural Gas Fund",t:"etf",m:"ext"},
  {s:"DBC",n:"Invesco DB Commodity Index Tracking Fund",t:"etf",m:"ext"},
  {s:"TLT",n:"iShares 20+ Year Treasury Bond ETF",t:"etf",m:"ext"},
  {s:"IEF",n:"iShares 7-10 Year Treasury Bond ETF",t:"etf",m:"ext"},
  {s:"SHY",n:"iShares 1-3 Year Treasury Bond ETF",t:"etf",m:"ext"},
  {s:"BIL",n:"SPDR Bloomberg 1-3 Month T-Bill ETF",t:"etf",m:"ext"},
  {s:"SGOV",n:"iShares 0-3 Month Treasury Bond ETF",t:"etf",m:"ext"},
  {s:"BND",n:"Vanguard Total Bond Market ETF",t:"etf",m:"ext"},
  {s:"AGG",n:"iShares Core U.S. Aggregate Bond ETF",t:"etf",m:"ext"},
  {s:"LQD",n:"iShares iBoxx $ Investment Grade Corporate Bond ETF",t:"etf",m:"ext"},
  {s:"HYG",n:"iShares iBoxx $ High Yield Corporate Bond ETF",t:"etf",m:"ext"},
  {s:"JNK",n:"SPDR Bloomberg High Yield Bond ETF",t:"etf",m:"ext"},
  {s:"TIP",n:"iShares TIPS Bond ETF",t:"etf",m:"ext"},
  {s:"EMB",n:"iShares J.P. Morgan USD Emerging Markets Bond ETF",t:"etf",m:"ext"},
  {s:"SCHD",n:"Schwab U.S. Dividend Equity ETF",t:"etf",m:"ext"},
  {s:"VYM",n:"Vanguard High Dividend Yield ETF",t:"etf",m:"ext"},
  {s:"VIG",n:"Vanguard Dividend Appreciation ETF",t:"etf",m:"ext"},
  {s:"JEPI",n:"JPMorgan Equity Premium Income ETF",t:"etf",m:"ext"},
  {s:"JEPQ",n:"JPMorgan Nasdaq Equity Premium Income ETF",t:"etf",m:"ext"},
  {s:"MTUM",n:"iShares MSCI USA Momentum Factor ETF",t:"etf",m:"ext"},
  {s:"QUAL",n:"iShares MSCI USA Quality Factor ETF",t:"etf",m:"ext"},
  {s:"IBIT",n:"iShares Bitcoin Trust ETF",t:"etf",m:"ext"},
  {s:"FBTC",n:"Fidelity Wise Origin Bitcoin Fund",t:"etf",m:"ext"},
  {s:"GBTC",n:"Grayscale Bitcoin Trust ETF",t:"etf",m:"ext"},
  {s:"BITO",n:"ProShares Bitcoin ETF",t:"etf",m:"ext"},
  {s:"ETHA",n:"iShares Ethereum Trust ETF",t:"etf",m:"ext"},
  {s:"ETHE",n:"Grayscale Ethereum Trust ETF",t:"etf",m:"ext"},
  {s:"YPF",n:"YPF",t:"accion_us",m:"ext"},
  {s:"PAM",n:"Pampa Energía",t:"accion_us",m:"ext"},
  {s:"GGAL",n:"Grupo Galicia",t:"accion_us",m:"ext"},
  {s:"TSM",n:"TSMC",t:"accion_us",m:"ext"},
  {s:"VIST",n:"Vista Energy",t:"accion_us",m:"ext"},
  {s:"BMA",n:"Banco Macro",t:"accion_us",m:"ext"},
  {s:"CEPU",n:"Central Puerto",t:"accion_us",m:"ext"},
  {s:"TGS",n:"Transp. Gas del Sur",t:"accion_us",m:"ext"},
  {s:"BTC",n:"Bitcoin",t:"cripto",m:"cripto"},
  {s:"ETH",n:"Ethereum",t:"cripto",m:"cripto"},
  {s:"USDT",n:"Tether",t:"cripto",m:"cripto"},
  {s:"BNB",n:"BNB",t:"cripto",m:"cripto"},
  {s:"XRP",n:"XRP",t:"cripto",m:"cripto"},
  {s:"USDC",n:"USDC",t:"cripto",m:"cripto"},
  {s:"SOL",n:"Solana",t:"cripto",m:"cripto"},
  {s:"TRX",n:"TRON",t:"cripto",m:"cripto"},
  {s:"ZEC",n:"Zcash",t:"cripto",m:"cripto"},
  {s:"HYPE",n:"Hyperliquid",t:"cripto",m:"cripto"},
  {s:"DOGE",n:"Dogecoin",t:"cripto",m:"cripto"},
  {s:"XMR",n:"Monero",t:"cripto",m:"cripto"},
  {s:"WBT",n:"WhiteBIT Coin",t:"cripto",m:"cripto"},
  {s:"USDS",n:"USDS",t:"cripto",m:"cripto"},
  {s:"LINK",n:"Chainlink",t:"cripto",m:"cripto"},
  {s:"ADA",n:"Cardano",t:"cripto",m:"cripto"},
  {s:"RAIN",n:"Rain",t:"cripto",m:"cripto"},
  {s:"LEO",n:"LEO Token",t:"cripto",m:"cripto"},
  {s:"XLM",n:"Stellar",t:"cripto",m:"cripto"},
  {s:"BCH",n:"Bitcoin Cash",t:"cripto",m:"cripto"},
  {s:"NEAR",n:"NEAR Protocol",t:"cripto",m:"cripto"},
  {s:"UNI",n:"Uniswap",t:"cripto",m:"cripto"},
  {s:"USDE",n:"Ethena USDe",t:"cripto",m:"cripto"},
  {s:"LTC",n:"Litecoin",t:"cripto",m:"cripto"},
  {s:"DAI",n:"Dai",t:"cripto",m:"cripto"},
  {s:"AVAX",n:"Avalanche",t:"cripto",m:"cripto"},
  {s:"USD1",n:"USD1",t:"cripto",m:"cripto"},
  {s:"CC",n:"Canton",t:"cripto",m:"cripto"},
  {s:"GRAM",n:"Gram (prev. Toncoin)",t:"cripto",m:"cripto"},
  {s:"HBAR",n:"Hedera",t:"cripto",m:"cripto"},
  {s:"SUI",n:"Sui",t:"cripto",m:"cripto"},
  {s:"SHIB",n:"Shiba Inu",t:"cripto",m:"cripto"},
  {s:"TAO",n:"Bittensor",t:"cripto",m:"cripto"},
  {s:"USDG",n:"Global Dollar",t:"cripto",m:"cripto"},
  {s:"CRO",n:"Cronos",t:"cripto",m:"cripto"},
  {s:"PYUSD",n:"PayPal USD",t:"cripto",m:"cripto"},
  {s:"M",n:"MemeCore",t:"cripto",m:"cripto"},
  {s:"BTW",n:"Bitway",t:"cripto",m:"cripto"},
  {s:"XAUT",n:"Tether Gold",t:"cripto",m:"cripto"},
  {s:"OKB",n:"OKB",t:"cripto",m:"cripto"},
  {s:"USYC",n:"Circle USYC",t:"cripto",m:"cripto"},
  {s:"RLUSD",n:"Ripple USD",t:"cripto",m:"cripto"},
  {s:"BUIDL",n:"BlackRock USD Institutional Digital Liquidity Fund",t:"cripto",m:"cripto"},
  {s:"USDY",n:"Ondo US Dollar Yield",t:"cripto",m:"cripto"},
  {s:"MNT",n:"Mantle",t:"cripto",m:"cripto"},
  {s:"AAVE",n:"Aave",t:"cripto",m:"cripto"},
  {s:"ENA",n:"Ethena",t:"cripto",m:"cripto"},
  {s:"ONDO",n:"Ondo",t:"cripto",m:"cripto"},
  {s:"PUMP",n:"Pump.fun",t:"cripto",m:"cripto"},
  {s:"ASTER",n:"Aster",t:"cripto",m:"cripto"},
  {s:"DOT",n:"Polkadot",t:"cripto",m:"cripto"},
  {s:"PAXG",n:"PAX Gold",t:"cripto",m:"cripto"},
  {s:"PEPE",n:"Pepe",t:"cripto",m:"cripto"},
  {s:"MORPHO",n:"Morpho",t:"cripto",m:"cripto"},
  {s:"WLFI",n:"World Liberty Financial",t:"cripto",m:"cripto"},
  {s:"SKY",n:"Sky",t:"cripto",m:"cripto"},
  {s:"ICP",n:"Internet Computer",t:"cripto",m:"cripto"},
  {s:"HTX",n:"HTX DAO",t:"cripto",m:"cripto"},
  {s:"USDD",n:"USDD",t:"cripto",m:"cripto"},
  {s:"ARB",n:"Arbitrum",t:"cripto",m:"cripto"},
  {s:"WLD",n:"Worldcoin",t:"cripto",m:"cripto"},
  {s:"VVV",n:"Venice Token",t:"cripto",m:"cripto"},
  {s:"EURSAFO",n:"Spiko Amundi Overnight Swap Fund (EUR)",t:"cripto",m:"cripto"},
  {s:"BGB",n:"Bitget Token",t:"cripto",m:"cripto"},
  {s:"U",n:"United Stables",t:"cripto",m:"cripto"},
  {s:"USDGO",n:"USDGO",t:"cripto",m:"cripto"},
  {s:"ETC",n:"Ethereum Classic",t:"cripto",m:"cripto"},
  {s:"USDF",n:"Falcon USD",t:"cripto",m:"cripto"},
  {s:"LIT",n:"Lighter",t:"cripto",m:"cripto"},
  {s:"BFUSD",n:"BFUSD",t:"cripto",m:"cripto"},
  {s:"GT",n:"Gate",t:"cripto",m:"cripto"},
  {s:"POL",n:"POL (ex-MATIC)",t:"cripto",m:"cripto"},
  {s:"KAS",n:"Kaspa",t:"cripto",m:"cripto"},
  {s:"AKE",n:"Akedo",t:"cripto",m:"cripto"},
  {s:"QNT",n:"Quant",t:"cripto",m:"cripto"},
  {s:"PI",n:"Pi Network",t:"cripto",m:"cripto"},
  {s:"KCS",n:"KuCoin",t:"cripto",m:"cripto"},
  {s:"BCAP",n:"Blockchain Capital",t:"cripto",m:"cripto"},
  {s:"ALGO",n:"Algorand",t:"cripto",m:"cripto"},
  {s:"JUP",n:"Jupiter",t:"cripto",m:"cripto"},
  {s:"JST",n:"JUST",t:"cripto",m:"cripto"},
  {s:"ATOM",n:"Cosmos Hub",t:"cripto",m:"cripto"},
  {s:"RENDER",n:"Render",t:"cripto",m:"cripto"},
  {s:"NEXO",n:"NEXO",t:"cripto",m:"cripto"},
  {s:"CAKE",n:"PancakeSwap",t:"cripto",m:"cripto"},
  {s:"FIL",n:"Filecoin",t:"cripto",m:"cripto"},
  {s:"EUTBL",n:"Spiko EU T-Bills Money Market Fund",t:"cripto",m:"cripto"},
  {s:"INJ",n:"Injective",t:"cripto",m:"cripto"},
  {s:"VET",n:"VeChain",t:"cripto",m:"cripto"},
  {s:"DASH",n:"Dash",t:"cripto",m:"cripto"},
  {s:"USTB",n:"Invesco Short Duration US Government Securities Fund",t:"cripto",m:"cripto"},
  {s:"GHO",n:"GHO",t:"cripto",m:"cripto"},
  {s:"JAAA",n:"Janus Henderson Anemoy AAA CLO Fund",t:"cripto",m:"cripto"},
  {s:"AERO",n:"Aerodrome Finance",t:"cripto",m:"cripto"},
  {s:"STABLE",n:"Stable",t:"cripto",m:"cripto"},
  {s:"APT",n:"Aptos",t:"cripto",m:"cripto"},
  {s:"ETHFI",n:"Ether.fi",t:"cripto",m:"cripto"},
  {s:"FLR",n:"Flare",t:"cripto",m:"cripto"},
  {s:"PENGU",n:"Pudgy Penguins",t:"cripto",m:"cripto"},
];

/* símbolo tal cual lo guarda la cartera -> clave del catálogo:
   GGAL.BA -> GGAL, BTC-USD -> BTC, al30d -> AL30D */
export function claveCatalogo(simbolo) {
  return String(simbolo || "").trim().toUpperCase().replace(/\.BA$/, "").replace(/-USD$/, "");
}

const _porSimbolo = new Map();
for (const e of CATALOGO) {
  const l = _porSimbolo.get(e.s);
  if (l) l.push(e); else _porSimbolo.set(e.s, [e]);
}

/* Las acciones por clase se escriben de tres formas según quién las liste, y
   son el mismo papel: BRK-B (Yahoo, y así la guarda la cartera), BRK.B (S&P,
   y así está en la lista de EE.UU.) y BRKB (BYMA, el CEDEAR). Las claves a
   probar para lo escrito, la propia primero. */
export function variantesClase(clave) {
  const c = String(clave || "");
  const m = c.match(/^([A-Z0-9]+)[.\-]([A-Z])$/);
  if (m) return [c, `${m[1]}.${m[2]}`, `${m[1]}-${m[2]}`, m[1] + m[2]];
  const n = c.match(/^([A-Z0-9]{2,})([A-Z])$/);
  if (n) return [c, `${n[1]}.${n[2]}`, `${n[1]}-${n[2]}`];
  return [c];
}

const _ORDEN_MERCADO = { byma: 0, ext: 1, cripto: 2 };

/* Todas las entradas de un símbolo, en cualquier mercado y escrito de
   cualquier forma (BRK-B encuentra BRK.B y BRKB), en el orden BYMA, exterior,
   cripto; dentro de un mercado, primero la escritura exacta. */
export function entradasCatalogo(simbolo) {
  const c = claveCatalogo(simbolo);
  if (!c) return [];
  const out = [];
  for (const v of variantesClase(c)) for (const e of _porSimbolo.get(v) || []) if (!out.includes(e)) out.push(e);
  return out.sort((a, b) => (_ORDEN_MERCADO[a.m] ?? 9) - (_ORDEN_MERCADO[b.m] ?? 9));
}

/* La entrada del catálogo para un símbolo (o null). Con mercado ("byma", "ext",
   "cripto") se filtra: AAPL en byma es el CEDEAR, en ext la acción. Sin mercado
   devuelve la primera que haya (BYMA antes que exterior, y cripto al final). */
export function buscarCatalogo(simbolo, mercado) {
  const l = entradasCatalogo(simbolo);
  if (!l.length) return null;
  if (!mercado) return l[0];
  return l.find(e => e.m === mercado) || null;
}
